/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tournaments: Tournament;
    activities: Activity;
    experts: Expert;
    faqs: Faq;
    events: Event;
    opportunities: Opportunity;
    'team-members': TeamMember;
    'team-posts': TeamPost;
    'team-responses': TeamResponse;
    'trust-points': TrustPoint;
    pillars: Pillar;
    stats: Stat;
    applications: Application;
    'application-status-history': ApplicationStatusHistory;
    favorites: Favorite;
    notifications: Notification;
    'community-leads': CommunityLead;
    'contact-settings': ContactSetting;
    'blog-posts': BlogPost;
    'blog-post-localizations': BlogPostLocalization;
    'blog-moderation-history': BlogModerationHistory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    experts: ExpertsSelect<false> | ExpertsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'team-posts': TeamPostsSelect<false> | TeamPostsSelect<true>;
    'team-responses': TeamResponsesSelect<false> | TeamResponsesSelect<true>;
    'trust-points': TrustPointsSelect<false> | TrustPointsSelect<true>;
    pillars: PillarsSelect<false> | PillarsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'application-status-history': ApplicationStatusHistorySelect<false> | ApplicationStatusHistorySelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'community-leads': CommunityLeadsSelect<false> | CommunityLeadsSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-post-localizations': BlogPostLocalizationsSelect<false> | BlogPostLocalizationsSelect<true>;
    'blog-moderation-history': BlogModerationHistorySelect<false> | BlogModerationHistorySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Platform users, moderators and administrators
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name (optional if firstName/lastName used)
   */
  name?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  avatar?: (number | null) | Media;
  avatarUrl?: string | null;
  avatarAlt?: string | null;
  avatarPositionX?: number | null;
  avatarPositionY?: number | null;
  avatarScale?: number | null;
  biography?: string | null;
  portfolio?: string | null;
  country?: string | null;
  city?: string | null;
  /**
   * Date of birth (ISO format)
   */
  dateOfBirth?: string | null;
  ageGroup?: string | null;
  school?: string | null;
  schoolGrade?: string | null;
  interests?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  preferredLanguage?: ('ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr') | null;
  preferredLanguageMode?: ('auto' | 'manual') | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  teamSearchAvailable?: boolean | null;
  publicProfile?: boolean | null;
  privacy?: {
    showCity?: boolean | null;
    showSchool?: boolean | null;
    showAge?: boolean | null;
    showEmail?: boolean | null;
    showSocialLinks?: boolean | null;
  };
  accountStatus: 'active' | 'blocked' | 'pending';
  emailVerified?: boolean | null;
  verificationCode?: string | null;
  verificationCodeExpired?: string | null;
  role: 'user' | 'moderator' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Case championships & competitions for students
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Mark this championship to appear on the homepage
   */
  isFeatured?: boolean | null;
  title: string;
  /**
   * e.g. "Кейс-чемпионат", "Хакатон"
   */
  type: string;
  description: string;
  /**
   * Event date(s)
   */
  date: string;
  /**
   * Registration cutoff date
   */
  registrationDeadline: string;
  maxParticipants: number;
  skills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  mentors?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Who this is suitable for
   */
  suitableFor?: string | null;
  /**
   * Format description (e.g. online, offline, hybrid)
   */
  format?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  title: string;
  shortDescription: string;
  fullDescription: string;
  format: string;
  date: string;
  imageUrl: string;
  category: 'educational' | 'project' | 'social' | 'online-meeting' | 'workshop' | 'team';
  status: 'coming' | 'ongoing' | 'completed';
  who: string;
  benefits?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  prerequisites: string;
  ctaText: string;
  ctaLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts".
 */
export interface Expert {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  name: string;
  role: string;
  expertise: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  page: 'home' | 'about' | 'championship' | 'activities' | 'find-team' | 'opportunities';
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Online & offline events (workshops, lectures, meetups)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  title: string;
  slug: string;
  shortDescription: string;
  /**
   * Detailed description (optional)
   */
  fullDescription?: string | null;
  imageUrl?: string | null;
  /**
   * e.g. workshop, lecture, masterclass
   */
  eventType: string;
  eventDate: string;
  timeZone?: string | null;
  /**
   * Registration cutoff date
   */
  registrationDeadline?: string | null;
  participantLimit?: number | null;
  format: 'online' | 'offline' | 'hybrid';
  country?: string | null;
  /**
   * Physical location
   */
  venue?: string | null;
  /**
   * Zoom/Google Meet link
   */
  onlineLink?: string | null;
  speaker?: string | null;
  languages?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * External & internal opportunities for students (grants, internships, olympiads, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  title: string;
  slug: string;
  organization: string;
  /**
   * e.g. championship, olympiad, internship, grant
   */
  opportunityType: string;
  shortDescription: string;
  /**
   * Detailed description (optional)
   */
  fullDescription?: string | null;
  logoUrl?: string | null;
  country?: string | null;
  format?: ('online' | 'offline' | 'hybrid') | null;
  ageMin?: number | null;
  ageMax?: number | null;
  /**
   * Cost description (e.g. "Free", "$50")
   */
  cost?: string | null;
  funding?: boolean | null;
  deadline?: string | null;
  languages?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * External application link
   */
  officialUrl?: string | null;
  internalApplicationsEnabled?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  name: string;
  age: number;
  country: string;
  city?: string | null;
  shortBio: string;
  interests?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  targetRoles: (
    'developer' | 'designer' | 'researcher' | 'product_manager' | 'marketer' | 'team_lead' | 'analyst' | 'other'
  )[];
  targetProject?: string | null;
  whyLooking: string;
  contact: string;
  contactType: 'telegram' | 'email' | 'discord';
  isApproved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-posts".
 */
export interface TeamPost {
  id: number;
  user: number | User;
  title: string;
  description: string;
  status?: ('draft' | 'published' | 'hidden') | null;
  championshipId?: string | null;
  projectName?: string | null;
  communicationLanguage?: string | null;
  timeZone?: string | null;
  workingFormat?: ('online' | 'offline' | 'hybrid') | null;
  openPositions?: number | null;
  requiredSkills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  ownSkills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  interests?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-responses".
 */
export interface TeamResponse {
  id: number;
  post: number | TeamPost;
  sender: number | User;
  recipient: number | User;
  kind?: ('response' | 'invitation') | null;
  message?: string | null;
  status?: ('pending' | 'accepted' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-points".
 */
export interface TrustPoint {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars".
 */
export interface Pillar {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  label: string;
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  value: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  ticketId: string;
  user?: (number | null) | User;
  itemType?: ('championship' | 'event' | 'opportunity' | 'program' | 'team-post') | null;
  itemId?: string | null;
  itemTitle?: string | null;
  status:
    | 'draft'
    | 'submitted'
    | 'under_review'
    | 'clarification_required'
    | 'approved'
    | 'rejected'
    | 'cancelled'
    | 'new'
    | 'confirmed'
    | 'contacted';
  name: string;
  email: string;
  grade?: string | null;
  age?: string | null;
  city?: string | null;
  contact?: string | null;
  interest?: string | null;
  tournamentId?: string | null;
  hasTeam?: string | null;
  teamSize?: string | null;
  portfolioLink?: string | null;
  coverLetter?: string | null;
  customAnswers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  adminComment?: string | null;
  internalNotes?: string | null;
  submittedAt?: string | null;
  cancelledAt?: string | null;
  attachments?: (number | Media)[] | null;
  source?: ('modal' | 'inline' | 'championship' | 'find-team' | 'api') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-status-history".
 */
export interface ApplicationStatusHistory {
  id: number;
  application: number | Application;
  user: number | User;
  actor?: (number | null) | User;
  previousStatus?: string | null;
  status: string;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  user: number | User;
  itemType: 'championship' | 'event' | 'opportunity' | 'participant' | 'team-post';
  itemId: string;
  itemTitle: string;
  href: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  type:
    | 'application_submitted'
    | 'application_status_changed'
    | 'clarification_requested'
    | 'team_response_received'
    | 'team_response_accepted'
    | 'team_response_rejected'
    | 'team_invitation_received'
    | 'upcoming_deadline'
    | 'upcoming_event'
    | 'announcement'
    | 'blog_post_submitted'
    | 'blog_post_pending_review'
    | 'blog_post_approved'
    | 'blog_post_published'
    | 'blog_post_rejected'
    | 'blog_post_needs_revision';
  relatedType?:
    | (
        | 'application'
        | 'championship'
        | 'event'
        | 'opportunity'
        | 'participant'
        | 'team-post'
        | 'team-response'
        | 'blog-post'
      )
    | null;
  relatedId?: string | null;
  href?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-leads".
 */
export interface CommunityLead {
  id: number;
  name: string;
  age: string;
  location: string;
  contact: string;
  interest?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact information displayed in the site footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  /**
   * Admin-only label to identify this settings entry.
   */
  label: string;
  email?: string | null;
  phone?: string | null;
  telegram?: string | null;
  address?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * Stable ID from the original frontend data file.
   */
  legacyId?: string | null;
  sortOrder?: number | null;
  /**
   * Original title
   */
  title: string;
  excerpt: string;
  /**
   * Markdown or plain text.
   */
  content: string;
  cover?: (number | null) | Media;
  coverAlt?: string | null;
  category:
    | 'news'
    | 'championships'
    | 'activities'
    | 'opportunities'
    | 'stories'
    | 'interviews'
    | 'tips'
    | 'education'
    | 'projects';
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'pending_review' | 'needs_revision' | 'approved' | 'published' | 'rejected' | 'archived';
  author: number | User;
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  /**
   * URL slug
   */
  slug: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * In minutes. Auto-calculated if not set.
   */
  readingTime?: number | null;
  views?: number | null;
  likes?: number | null;
  publishedAt?: string | null;
  /**
   * Last comment from moderator to author
   */
  moderationComment?: string | null;
  isApproved?: boolean | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-post-localizations".
 */
export interface BlogPostLocalization {
  id: number;
  post: number | BlogPost;
  language: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  title: string;
  excerpt: string;
  content: string;
  slug: string;
  coverAlt?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationStatus: 'pending' | 'in_progress' | 'ready' | 'failed';
  errorMessage?: string | null;
  generatedAt?: string | null;
  attempts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-moderation-history".
 */
export interface BlogModerationHistory {
  id: number;
  post: number | BlogPost;
  author?: (number | null) | User;
  actor?: (number | null) | User;
  previousStatus?: string | null;
  status: string;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'experts';
        value: number | Expert;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'team-posts';
        value: number | TeamPost;
      } | null)
    | ({
        relationTo: 'team-responses';
        value: number | TeamResponse;
      } | null)
    | ({
        relationTo: 'trust-points';
        value: number | TrustPoint;
      } | null)
    | ({
        relationTo: 'pillars';
        value: number | Pillar;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'application-status-history';
        value: number | ApplicationStatusHistory;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'community-leads';
        value: number | CommunityLead;
      } | null)
    | ({
        relationTo: 'contact-settings';
        value: number | ContactSetting;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-post-localizations';
        value: number | BlogPostLocalization;
      } | null)
    | ({
        relationTo: 'blog-moderation-history';
        value: number | BlogModerationHistory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  firstName?: T;
  lastName?: T;
  avatar?: T;
  avatarUrl?: T;
  avatarAlt?: T;
  avatarPositionX?: T;
  avatarPositionY?: T;
  avatarScale?: T;
  biography?: T;
  portfolio?: T;
  country?: T;
  city?: T;
  dateOfBirth?: T;
  ageGroup?: T;
  school?: T;
  schoolGrade?: T;
  interests?:
    | T
    | {
        value?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  preferredLanguage?: T;
  preferredLanguageMode?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  teamSearchAvailable?: T;
  publicProfile?: T;
  privacy?:
    | T
    | {
        showCity?: T;
        showSchool?: T;
        showAge?: T;
        showEmail?: T;
        showSocialLinks?: T;
      };
  accountStatus?: T;
  emailVerified?: T;
  verificationCode?: T;
  verificationCodeExpired?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  isFeatured?: T;
  title?: T;
  type?: T;
  description?: T;
  date?: T;
  registrationDeadline?: T;
  maxParticipants?: T;
  skills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  mentors?:
    | T
    | {
        value?: T;
        id?: T;
      };
  suitableFor?: T;
  format?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  title?: T;
  shortDescription?: T;
  fullDescription?: T;
  format?: T;
  date?: T;
  imageUrl?: T;
  category?: T;
  status?: T;
  who?: T;
  benefits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  prerequisites?: T;
  ctaText?: T;
  ctaLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts_select".
 */
export interface ExpertsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  name?: T;
  role?: T;
  expertise?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  page?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  title?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  imageUrl?: T;
  eventType?: T;
  eventDate?: T;
  timeZone?: T;
  registrationDeadline?: T;
  participantLimit?: T;
  format?: T;
  country?: T;
  venue?: T;
  onlineLink?: T;
  speaker?: T;
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        value?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  title?: T;
  slug?: T;
  organization?: T;
  opportunityType?: T;
  shortDescription?: T;
  fullDescription?: T;
  logoUrl?: T;
  country?: T;
  format?: T;
  ageMin?: T;
  ageMax?: T;
  cost?: T;
  funding?: T;
  deadline?: T;
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        value?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        value?: T;
        id?: T;
      };
  officialUrl?: T;
  internalApplicationsEnabled?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  name?: T;
  age?: T;
  country?: T;
  city?: T;
  shortBio?: T;
  interests?:
    | T
    | {
        value?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  targetRoles?: T;
  targetProject?: T;
  whyLooking?: T;
  contact?: T;
  contactType?: T;
  isApproved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-posts_select".
 */
export interface TeamPostsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  description?: T;
  status?: T;
  championshipId?: T;
  projectName?: T;
  communicationLanguage?: T;
  timeZone?: T;
  workingFormat?: T;
  openPositions?: T;
  requiredSkills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  ownSkills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  interests?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-responses_select".
 */
export interface TeamResponsesSelect<T extends boolean = true> {
  post?: T;
  sender?: T;
  recipient?: T;
  kind?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-points_select".
 */
export interface TrustPointsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars_select".
 */
export interface PillarsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  label?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  value?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  ticketId?: T;
  user?: T;
  itemType?: T;
  itemId?: T;
  itemTitle?: T;
  status?: T;
  name?: T;
  email?: T;
  grade?: T;
  age?: T;
  city?: T;
  contact?: T;
  interest?: T;
  tournamentId?: T;
  hasTeam?: T;
  teamSize?: T;
  portfolioLink?: T;
  coverLetter?: T;
  customAnswers?: T;
  adminComment?: T;
  internalNotes?: T;
  submittedAt?: T;
  cancelledAt?: T;
  attachments?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-status-history_select".
 */
export interface ApplicationStatusHistorySelect<T extends boolean = true> {
  application?: T;
  user?: T;
  actor?: T;
  previousStatus?: T;
  status?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  itemType?: T;
  itemId?: T;
  itemTitle?: T;
  href?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  relatedType?: T;
  relatedId?: T;
  href?: T;
  data?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-leads_select".
 */
export interface CommunityLeadsSelect<T extends boolean = true> {
  name?: T;
  age?: T;
  location?: T;
  contact?: T;
  interest?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  label?: T;
  email?: T;
  phone?: T;
  telegram?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  title?: T;
  excerpt?: T;
  content?: T;
  cover?: T;
  coverAlt?: T;
  category?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  status?: T;
  author?: T;
  originalLanguage?: T;
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  readingTime?: T;
  views?: T;
  likes?: T;
  publishedAt?: T;
  moderationComment?: T;
  isApproved?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-post-localizations_select".
 */
export interface BlogPostLocalizationsSelect<T extends boolean = true> {
  post?: T;
  language?: T;
  title?: T;
  excerpt?: T;
  content?: T;
  slug?: T;
  coverAlt?: T;
  seoTitle?: T;
  seoDescription?: T;
  translationStatus?: T;
  errorMessage?: T;
  generatedAt?: T;
  attempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-moderation-history_select".
 */
export interface BlogModerationHistorySelect<T extends boolean = true> {
  post?: T;
  author?: T;
  actor?: T;
  previousStatus?: T;
  status?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}