/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tournaments: Tournament;
    activities: Activity;
    experts: Expert;
    faqs: Faq;
    events: Event;
    opportunities: Opportunity;
    'team-members': TeamMember;
    'trust-points': TrustPoint;
    pillars: Pillar;
    scenarios: Scenario;
    stats: Stat;
    'contact-settings': ContactSetting;
    'operator-settings': OperatorSetting;
    'audit-logs': AuditLog;
    'page-texts': PageText;
    'content-localizations': ContentLocalization;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    experts: ExpertsSelect<false> | ExpertsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'trust-points': TrustPointsSelect<false> | TrustPointsSelect<true>;
    pillars: PillarsSelect<false> | PillarsSelect<true>;
    scenarios: ScenariosSelect<false> | ScenariosSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
    'operator-settings': OperatorSettingsSelect<false> | OperatorSettingsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'page-texts': PageTextsSelect<false> | PageTextsSelect<true>;
    'content-localizations': ContentLocalizationsSelect<false> | ContentLocalizationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Staff accounts for Payload CMS access only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  accountStatus: 'active' | 'blocked' | 'pending';
  role: 'moderator' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Case championships & competitions for students
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  /**
   * Отметьте, чтобы чемпионат появился на главной странице
   */
  isFeatured?: boolean | null;
  title: string;
  /**
   * Генерируется автоматически из заголовка, если пусто.
   */
  slug?: string | null;
  /**
   * Например: "Кейс-чемпионат", "Хакатон"
   */
  type: string;
  description: string;
  /**
   * Если пусто, используется описание.
   */
  pitch?: string | null;
  /**
   * Даты события (текстом)
   */
  date: string;
  /**
   * Дата окончания регистрации
   */
  registrationDeadline: string;
  registrationStatus: 'open' | 'suspended' | 'closed';
  maxParticipants: number;
  skills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  mentors?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  suitableFor?: string | null;
  /**
   * Карточка "Формат участия" на странице чемпионата. Первая строка - крупный текст, остальные строки - подпись. Пустое поле скрывает карточку.
   */
  format?: string | null;
  targetAudience?: string | null;
  ageLimit?: string | null;
  teamsAllowed?: string | null;
  language?: string | null;
  expectedResult?: string | null;
  /**
   * Один пункт на строку.
   */
  themesText?: string | null;
  /**
   * Один пункт на строку.
   */
  evaluationCriteriaText?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  title: string;
  shortDescription: string;
  fullDescription: string;
  imageUrl: string;
  category: 'educational' | 'project' | 'social' | 'online-meeting' | 'workshop' | 'team';
  status: 'coming' | 'ongoing' | 'completed';
  format: string;
  date: string;
  who: string;
  benefits?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  prerequisites: string;
  ctaText: string;
  ctaLink?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts".
 */
export interface Expert {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  name: string;
  /**
   * Роль в чемпионате: жюри, наставник или эксперт
   */
  type: 'jury' | 'mentor' | 'expert';
  role: string;
  /**
   * К какому чемпионату привязан эксперт
   */
  tournamentId?: (number | null) | Tournament;
  expertise: string;
  description: string;
  /**
   * Фото эксперта, наставника или жюри
   */
  photo?: (number | null) | Media;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  page: 'home' | 'about' | 'championship' | 'activities' | 'find-team' | 'opportunities';
  question: string;
  answer: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Online & offline events (workshops, lectures, meetups)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  title: string;
  /**
   * Генерируется автоматически из заголовка, если пусто.
   */
  slug?: string | null;
  shortDescription: string;
  /**
   * Подробное описание (необязательно)
   */
  fullDescription?: string | null;
  imageUrl?: string | null;
  /**
   * Например: воркшоп, лекция, мастер-класс
   */
  eventType: string;
  /**
   * Техническая дата для сортировки и статуса. Время можно не показывать на сайте ниже.
   */
  eventDate: string;
  /**
   * Необязательно. Если заполнено, сайт покажет этот текст вместо автоматической даты.
   */
  displayDate?: string | null;
  /**
   * Выключено по умолчанию: на карточках и в модалке показывается только дата.
   */
  showTime?: boolean | null;
  timeZone?: string | null;
  /**
   * Дата без времени для блока предварительного опыта/условий.
   */
  registrationDeadline?: string | null;
  participantLimit?: number | null;
  format: 'online' | 'offline' | 'hybrid';
  country?: string | null;
  /**
   * Физический адрес
   */
  venue?: string | null;
  /**
   * Ссылка Zoom/Google Meet
   */
  onlineLink?: string | null;
  /**
   * Внешняя ссылка на регистрацию/заявку
   */
  registrationUrl: string;
  speaker?: string | null;
  languages?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Текст для блока "Кому подходит" в модальном окне активности.
   */
  audience?: string | null;
  /**
   * Один пункт на строку.
   */
  outcomesText?: string | null;
  /**
   * Если оставить пустым, сайт покажет дедлайн регистрации, если он заполнен.
   */
  prerequisites?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * External & internal opportunities for students (grants, internships, olympiads, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  title: string;
  /**
   * Генерируется автоматически из заголовка, если пусто.
   */
  slug?: string | null;
  organization: string;
  /**
   * Например: чемпионат, олимпиада, стажировка, грант
   */
  opportunityType: string;
  source?: ('navykus' | 'verified' | 'partner') | null;
  /**
   * ID категории фронтенда, например: championships, olympiads, internships, projects
   */
  category?: string | null;
  direction?: ('business' | 'science' | 'tech' | 'social' | 'creative' | 'leadership') | null;
  participation?: ('individual' | 'team' | 'both') | null;
  shortDescription: string;
  /**
   * Подробное описание (необязательно)
   */
  fullDescription?: string | null;
  logoUrl?: string | null;
  /**
   * Изображение карточки/деталей. Если пусто, используется логотип.
   */
  imageUrl?: string | null;
  country?: string | null;
  city?: string | null;
  format?: ('online' | 'offline' | 'hybrid') | null;
  ageMin?: number | null;
  ageMax?: number | null;
  /**
   * Описание стоимости (например: "Бесплатно", "$50")
   */
  cost?: string | null;
  funding?: boolean | null;
  deadline?: string | null;
  startDate?: string | null;
  finalDeadline?: boolean | null;
  registrationOpen?: boolean | null;
  seats?: number | null;
  savedCount?: number | null;
  editorPick?: boolean | null;
  recommended?: boolean | null;
  portfolioValue?: number | null;
  publishedAt?: string | null;
  languages?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  grades?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Внешняя ссылка на заявку
   */
  officialUrl: string;
  internalApplicationsEnabled?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  sortOrder?: number | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  name: string;
  email: string;
  age: number;
  country: string;
  city?: string | null;
  shortBio: string;
  interests?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  targetRoles: (
    'developer' | 'designer' | 'researcher' | 'product_manager' | 'marketer' | 'team_lead' | 'analyst' | 'other'
  )[];
  targetProject?: string | null;
  whyLooking: string;
  contact: string;
  contactType: 'telegram' | 'email';
  /**
   * Статус проверки анкеты участника.
   */
  moderationStatus: 'pending' | 'approved' | 'rejected' | 'needs_edit';
  moderationComment?: string | null;
  reviewedAt?: string | null;
  isApproved?: boolean | null;
  /**
   * Внешняя ссылка на портфолио из анкеты.
   */
  portfolioLink?: string | null;
  /**
   * Файлы портфолио, загруженные из публичной анкеты.
   */
  portfolioFiles?: (number | Media)[] | null;
  sourceType?:
    ('modal' | 'championship' | 'event' | 'opportunity' | 'find-team' | 'home' | 'about' | 'activities' | 'api') | null;
  /**
   * ID сущности-источника публичного CTA, если доступно.
   */
  sourceId?: string | null;
  /**
   * Человекочитаемое название/контекст источника.
   */
  sourceContext?: string | null;
  /**
   * К какому чемпионату привязана заявка
   */
  tournamentId?: (number | null) | Tournament;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-points".
 */
export interface TrustPoint {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  title?: string | null;
  description?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars".
 */
export interface Pillar {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  label: string;
  title: string;
  description: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenarios".
 */
export interface Scenario {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  /**
   * Название сценария, например: "Хочу попробовать"
   */
  title: string;
  /**
   * Кому подходит этот сценарий
   */
  who: string;
  /**
   * Почему стоит участвовать
   */
  why: string;
  /**
   * Текст кнопки действия
   */
  ctaText: string;
  actionType: 'apply' | 'team' | 'activity' | 'general';
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  /**
   * Например: "15+", "1000+"
   */
  value: string;
  /**
   * Например: "стран", "участников"
   */
  label: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact information displayed in the site footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  /**
   * Admin-only label to identify this settings entry.
   */
  label: string;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Operator details displayed in the Privacy Policy (personal data operator section).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operator-settings".
 */
export interface OperatorSetting {
  id: number;
  /**
   * Admin-only label to identify this settings entry.
   */
  label: string;
  /**
   * Full name of the operator (for self-employed: full name; for legal entities: company name).
   */
  operatorName?: string | null;
  /**
   * Taxpayer Identification Number (ИНН).
   */
  operatorInn?: string | null;
  /**
   * Primary State Registration Number. Not required for self-employed individuals.
   */
  operatorOgrn?: string | null;
  /**
   * Legal and postal address for sending written requests from data subjects.
   */
  operatorAddress?: string | null;
  /**
   * Registration number in the Roskomnadzor personal data operators register (assigned after submitting the notification).
   */
  operatorRegistryNumber?: string | null;
  /**
   * Date of entry in the Roskomnadzor register (assigned after submitting the notification).
   */
  operatorRegistryDate?: string | null;
  /**
   * Email address where data subjects can send requests regarding their personal data.
   */
  contactsEmail?: string | null;
  /**
   * Postal address for submitting written requests from data subjects.
   */
  contactsPostalAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: string;
  collection: string;
  documentId: string;
  actorId?: string | null;
  actorEmail?: string | null;
  changedFields?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  summary: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Русские тексты статичных страниц. Карточки, события, FAQ и формы редактируются в своих коллекциях. Для иерархического просмотра используйте «Дерево текстов» в боковом меню.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-texts".
 */
export interface PageText {
  id: number;
  /**
   * Служебный ID. Не редактировать.
   */
  legacyId?: string | null;
  /**
   * Порядок в списке CMS.
   */
  sortOrder?: number | null;
  isPublished?: boolean | null;
  page: 'global' | 'home' | 'about' | 'championship' | 'activities' | 'find-team' | 'legal';
  /**
   * Нужен сайту, чтобы подставить текст в правильное место. Не редактировать.
   */
  translationKey: string;
  /**
   * Имя блока внутри страницы (на русском). Используется для группировки текстов в дереве редактирования.
   */
  blockName?: string | null;
  /**
   * Подсказка для поиска нужной строки.
   */
  label?: string | null;
  value?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-generated localized copies for public CMS content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-localizations".
 */
export interface ContentLocalization {
  id: number;
  sourceCollection:
    | 'team-members'
    | 'activities'
    | 'events'
    | 'experts'
    | 'faqs'
    | 'opportunities'
    | 'pillars'
    | 'scenarios'
    | 'stats'
    | 'trust-points'
    | 'tournaments'
    | 'page-texts';
  sourceId: string;
  language: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  localizedData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  translationStatus: 'pending' | 'in_progress' | 'ready' | 'failed';
  contentHash?: string | null;
  errorMessage?: string | null;
  generatedAt?: string | null;
  attempts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'experts';
        value: number | Expert;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'trust-points';
        value: number | TrustPoint;
      } | null)
    | ({
        relationTo: 'pillars';
        value: number | Pillar;
      } | null)
    | ({
        relationTo: 'scenarios';
        value: number | Scenario;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'contact-settings';
        value: number | ContactSetting;
      } | null)
    | ({
        relationTo: 'operator-settings';
        value: number | OperatorSetting;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'page-texts';
        value: number | PageText;
      } | null)
    | ({
        relationTo: 'content-localizations';
        value: number | ContentLocalization;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  accountStatus?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  isFeatured?: T;
  title?: T;
  slug?: T;
  type?: T;
  description?: T;
  pitch?: T;
  date?: T;
  registrationDeadline?: T;
  registrationStatus?: T;
  maxParticipants?: T;
  skills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  mentors?:
    | T
    | {
        value?: T;
        id?: T;
      };
  suitableFor?: T;
  format?: T;
  targetAudience?: T;
  ageLimit?: T;
  teamsAllowed?: T;
  language?: T;
  expectedResult?: T;
  themesText?: T;
  evaluationCriteriaText?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  title?: T;
  shortDescription?: T;
  fullDescription?: T;
  imageUrl?: T;
  category?: T;
  status?: T;
  format?: T;
  date?: T;
  who?: T;
  benefits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  prerequisites?: T;
  ctaText?: T;
  ctaLink?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts_select".
 */
export interface ExpertsSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  name?: T;
  type?: T;
  role?: T;
  tournamentId?: T;
  expertise?: T;
  description?: T;
  photo?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  page?: T;
  question?: T;
  answer?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  title?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  imageUrl?: T;
  eventType?: T;
  eventDate?: T;
  displayDate?: T;
  showTime?: T;
  timeZone?: T;
  registrationDeadline?: T;
  participantLimit?: T;
  format?: T;
  country?: T;
  venue?: T;
  onlineLink?: T;
  registrationUrl?: T;
  speaker?: T;
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        value?: T;
        id?: T;
      };
  audience?: T;
  outcomesText?: T;
  prerequisites?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  title?: T;
  slug?: T;
  organization?: T;
  opportunityType?: T;
  source?: T;
  category?: T;
  direction?: T;
  participation?: T;
  shortDescription?: T;
  fullDescription?: T;
  logoUrl?: T;
  imageUrl?: T;
  country?: T;
  city?: T;
  format?: T;
  ageMin?: T;
  ageMax?: T;
  cost?: T;
  funding?: T;
  deadline?: T;
  startDate?: T;
  finalDeadline?: T;
  registrationOpen?: T;
  seats?: T;
  savedCount?: T;
  editorPick?: T;
  recommended?: T;
  portfolioValue?: T;
  publishedAt?: T;
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  grades?:
    | T
    | {
        value?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        value?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        value?: T;
        id?: T;
      };
  officialUrl?: T;
  internalApplicationsEnabled?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  sortOrder?: T;
  originalLanguage?: T;
  name?: T;
  email?: T;
  age?: T;
  country?: T;
  city?: T;
  shortBio?: T;
  interests?:
    | T
    | {
        value?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  targetRoles?: T;
  targetProject?: T;
  whyLooking?: T;
  contact?: T;
  contactType?: T;
  moderationStatus?: T;
  moderationComment?: T;
  reviewedAt?: T;
  isApproved?: T;
  portfolioLink?: T;
  portfolioFiles?: T;
  sourceType?: T;
  sourceId?: T;
  sourceContext?: T;
  tournamentId?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-points_select".
 */
export interface TrustPointsSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  title?: T;
  description?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars_select".
 */
export interface PillarsSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  label?: T;
  title?: T;
  description?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenarios_select".
 */
export interface ScenariosSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  title?: T;
  who?: T;
  why?: T;
  ctaText?: T;
  actionType?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  value?: T;
  label?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  label?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operator-settings_select".
 */
export interface OperatorSettingsSelect<T extends boolean = true> {
  label?: T;
  operatorName?: T;
  operatorInn?: T;
  operatorOgrn?: T;
  operatorAddress?: T;
  operatorRegistryNumber?: T;
  operatorRegistryDate?: T;
  contactsEmail?: T;
  contactsPostalAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collection?: T;
  documentId?: T;
  actorId?: T;
  actorEmail?: T;
  changedFields?:
    | T
    | {
        value?: T;
        id?: T;
      };
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-texts_select".
 */
export interface PageTextsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  page?: T;
  translationKey?: T;
  blockName?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-localizations_select".
 */
export interface ContentLocalizationsSelect<T extends boolean = true> {
  sourceCollection?: T;
  sourceId?: T;
  language?: T;
  localizedData?: T;
  translationStatus?: T;
  contentHash?: T;
  errorMessage?: T;
  generatedAt?: T;
  attempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}