/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tournaments: Tournament;
    activities: Activity;
    experts: Expert;
    faqs: Faq;
    events: Event;
    opportunities: Opportunity;
    'team-members': TeamMember;
    'contact-settings': ContactSetting;
    'operator-settings': OperatorSetting;
    'audit-logs': AuditLog;
    'page-texts': PageText;
    'page-media-slots': PageMediaSlot;
    'content-localizations': ContentLocalization;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    experts: ExpertsSelect<false> | ExpertsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
    'operator-settings': OperatorSettingsSelect<false> | OperatorSettingsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'page-texts': PageTextsSelect<false> | PageTextsSelect<true>;
    'page-media-slots': PageMediaSlotsSelect<false> | PageMediaSlotsSelect<true>;
    'content-localizations': ContentLocalizationsSelect<false> | ContentLocalizationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Staff accounts for Payload CMS access only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  accountStatus: 'active' | 'blocked' | 'pending';
  role: 'moderator' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Медиафайлы, привязанные к страницам. Используйте «Дерево медиа» в боковом меню для иерархического просмотра и редактирования.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Необязательно. Страница сайта, к которой относится это медиа.
   */
  page?: ('global' | 'home' | 'about' | 'championship' | 'activities' | 'find-team' | 'legal') | null;
  /**
   * Имя блока внутри страницы (на русском). Используется для группировки в дереве медиа.
   */
  blockName?: string | null;
  /**
   * Порядок в списке CMS.
   */
  sortOrder?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Текущий чемпионат: всё, что показывается в блоке чемпионата на главной и на странице «Чемпионат». Прошлые чемпионаты — в разделе «Архив чемпионатов».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  /**
   * Активный чемпионат может быть только один. Чтобы сделать активным другой, откройте «Архив чемпионатов» и нажмите «Сделать активным» — текущий автоматически уйдёт в архив.
   */
  isFeatured?: boolean | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  sortOrder?: number | null;
  /**
   * Крупный заголовок в шапке страницы чемпионата и в карточке на главной.
   */
  title: string;
  /**
   * Одно-два предложения под названием в шапке страницы чемпионата. Если пусто — показывается «Описание».
   */
  pitch?: string | null;
  /**
   * Плашка в шапке и доступность формы заявки.
   */
  registrationStatus: 'open' | 'suspended' | 'closed';
  /**
   * Текстом. Показывается в плашке «Подача анкет открыта • До …», в карточке фактов и на главной.
   */
  registrationDeadline: string;
  /**
   * Справа от названия, пропорции примерно 4:3. Если пусто — берётся обложка, затем фото из «Дерева медиа».
   */
  heroImage?: (number | null) | Media;
  slug?: string | null;
  /**
   * Карточка «Даты проведения» и строка «Сроки» на главной.
   */
  date: string;
  /**
   * Карточка «Формат участия» и плашка в карточке на главной.
   */
  format?: string | null;
  /**
   * Карточка «Кто участвует».
   */
  ageLimit?: string | null;
  language?: string | null;
  teamsAllowed?: string | null;
  /**
   * Просто число. Карточка «Мест в отборе» на странице чемпионата и колонка в карточке на главной. 0 — не показывается.
   */
  maxParticipants: number;
  /**
   * Если пусто — показывается название чемпионата.
   */
  aboutHeading?: string | null;
  /**
   * Основной текст о чемпионате. Также показывается в карточке на главной.
   */
  description: string;
  /**
   * Слева от описания, пропорции примерно 16:10. Если пусто — фото из «Дерева медиа».
   */
  aboutImage?: (number | null) | Media;
  /**
   * Ключевые направления: одно на строку. Каждая строка — отдельная пронумерованная карточка и вариант в поле «Направление» анкеты участника.
   */
  themesText?: string | null;
  /**
   * Один критерий на строку.
   */
  evaluationCriteriaText?: string | null;
  /**
   * Блок «Ожидаемый результат». Пустое поле скрывает блок.
   */
  expectedResult?: string | null;
  /**
   * Широкая полоса сверху карточки (примерно 32:7). Если пусто — фото из «Дерева медиа».
   */
  coverImage?: (number | null) | Media;
  /**
   * Колонка «Кому подходит». Пустое поле скрывает колонку.
   */
  suitableFor?: string | null;
  /**
   * Например «Кейс-чемпионат». Используется в фильтре на странице «Поиск команды».
   */
  type: string;
  /**
   * Добавьте по карточке на каждого человека. Порядок на сайте — как здесь (перетаскивайте карточки).
   */
  juryMembers?:
    | {
        name: string;
        role?: string | null;
        /**
         * Небольшой портрет, лучше квадратный. Необязательно.
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  mentors?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  targetAudience?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  title: string;
  shortDescription: string;
  fullDescription: string;
  imageUrl: string;
  category: 'educational' | 'project' | 'social' | 'online-meeting' | 'workshop' | 'team';
  status: 'coming' | 'ongoing' | 'completed';
  format: string;
  date: string;
  who: string;
  benefits?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  prerequisites: string;
  ctaText: string;
  ctaLink?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts".
 */
export interface Expert {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  name: string;
  /**
   * Роль в чемпионате: жюри, наставник или эксперт
   */
  type: 'jury' | 'mentor' | 'expert';
  role: string;
  /**
   * К какому чемпионату привязан эксперт
   */
  tournamentId?: (number | null) | Tournament;
  expertise: string;
  description: string;
  /**
   * Фото эксперта, наставника или жюри
   */
  photo?: (number | null) | Media;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  page: 'home' | 'about' | 'championship' | 'activities' | 'find-team' | 'opportunities';
  question: string;
  answer: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Карточки на странице «Активности»: воркшопы, лекции, хакатоны, встречи. Пишите на исходном языке — переводы на все языки сайта делаются автоматически сразу после сохранения.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  sortOrder?: number | null;
  title: string;
  /**
   * Плашка на карточке и фильтр на странице.
   */
  eventType: 'educational' | 'project' | 'social' | 'online-meeting' | 'workshop' | 'team';
  /**
   * Переводится на сайте автоматически.
   */
  format: 'online' | 'offline' | 'hybrid';
  /**
   * 1–2 предложения для карточки.
   */
  shortDescription: string;
  /**
   * Обложка карточки (16:9). Если пусто — цветной фон категории.
   */
  image?: (number | null) | Media;
  imageUrl?: string | null;
  slug?: string | null;
  /**
   * По ней сайт сортирует активности и ставит статус «Скоро» / «Завершено».
   */
  eventDate: string;
  showTime?: boolean | null;
  /**
   * Если заполнено, сайт покажет этот текст вместо автоматической даты (переводится автоматически).
   */
  displayDate?: string | null;
  country?: string | null;
  /**
   * Адрес или площадка.
   */
  venue?: string | null;
  /**
   * Zoom / Google Meet. На сайте не показывается.
   */
  onlineLink?: string | null;
  /**
   * Показывается в блоке «Предварительный опыт», если тот пуст.
   */
  registrationDeadline?: string | null;
  /**
   * Показывается в блоке «Кому подходит» («до N участников»).
   */
  participantLimit?: number | null;
  /**
   * Куда ведёт кнопка «Принять участие».
   */
  registrationUrl: string;
  timeZone?: string | null;
  /**
   * Если пусто — показывается короткое описание.
   */
  fullDescription?: string | null;
  audience?: string | null;
  /**
   * Один пункт на строку.
   */
  outcomesText?: string | null;
  /**
   * Если пусто — сайт покажет дедлайн регистрации.
   */
  prerequisites?: string | null;
  speaker?: string | null;
  languages?:
    | {
        value: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
        id?: string | null;
      }[]
    | null;
  /**
   * Добавляются в блок «Что вы получите».
   */
  materials?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Каталог «Возможности»: олимпиады, стажировки, гранты, летние школы. Пишите на исходном языке — переводы на все языки сайта делаются автоматически сразу после сохранения.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  isPublished?: boolean | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  sortOrder?: number | null;
  title: string;
  /**
   * Показывается под названием.
   */
  organization: string;
  /**
   * Фильтр «Категория» в каталоге.
   */
  category:
    | 'championships'
    | 'olympiads'
    | 'contests'
    | 'internships'
    | 'projects'
    | 'research'
    | 'volunteering'
    | 'grants'
    | 'scholarships'
    | 'hackathons'
    | 'exchanges'
    | 'summer'
    | 'online';
  direction?: ('business' | 'science' | 'tech' | 'social' | 'creative' | 'leadership') | null;
  /**
   * 1–2 предложения для карточки.
   */
  shortDescription: string;
  /**
   * Обложка карточки (16:9).
   */
  image?: (number | null) | Media;
  imageUrl?: string | null;
  logoUrl?: string | null;
  /**
   * Плашка на карточке.
   */
  source?: ('navykus' | 'verified' | 'partner') | null;
  editorPick?: boolean | null;
  recommended?: boolean | null;
  /**
   * Пусто — «приём заявок постоянно».
   */
  deadline?: string | null;
  startDate?: string | null;
  registrationOpen?: boolean | null;
  format?: ('online' | 'offline' | 'hybrid') | null;
  participation?: ('individual' | 'team' | 'both') | null;
  cost?: ('free' | 'paid' | 'scholarship') | null;
  country?: string | null;
  city?: string | null;
  ageMin?: number | null;
  ageMax?: number | null;
  /**
   * Попадает в подборку «Скоро дедлайн» за 14 дней до срока.
   */
  finalDeadline?: boolean | null;
  languages?:
    | {
        value: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
        id?: string | null;
      }[]
    | null;
  /**
   * Номера классов, например 8, 9, 10. Используется фильтром «Класс».
   */
  grades?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Если пусто — показывается короткое описание.
   */
  fullDescription?: string | null;
  /**
   * Первые три показываются тегами на карточке.
   */
  skills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Блок «Что получите».
   */
  benefits?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Куда ведёт кнопка подачи заявки.
   */
  officialUrl: string;
  slug?: string | null;
  /**
   * Не показываются, но помогают найти возможность поиском.
   */
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 70 и выше — попадает в фильтр «Ценно для портфолио».
   */
  portfolioValue?: number | null;
  /**
   * Чем больше, тем выше в сортировке «Популярные».
   */
  savedCount?: number | null;
  /**
   * Для сортировки «Новые». Если пусто — дата создания.
   */
  publishedAt?: string | null;
  opportunityType?: string | null;
  seats?: number | null;
  funding?: boolean | null;
  internalApplicationsEnabled?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  sortOrder?: number | null;
  /**
   * Язык, используемый как источник для AI-перевода.
   */
  originalLanguage: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  name: string;
  email?: string | null;
  age: number;
  country: string;
  city?: string | null;
  shortBio: string;
  interests?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  targetRoles: (
    'developer' | 'designer' | 'researcher' | 'product_manager' | 'marketer' | 'team_lead' | 'analyst' | 'other'
  )[];
  targetProject?: string | null;
  whyLooking: string;
  contact?: string | null;
  contactType?: ('telegram' | 'email') | null;
  /**
   * Подтверждение согласия на обработку персональных данных и принятие регламента.
   */
  privacyConsent?: boolean | null;
  /**
   * Статус проверки анкеты участника.
   */
  moderationStatus: 'pending' | 'approved' | 'rejected' | 'needs_edit';
  moderationComment?: string | null;
  reviewedAt?: string | null;
  isApproved?: boolean | null;
  /**
   * Внешняя ссылка на портфолио из анкеты.
   */
  portfolioLink?: string | null;
  /**
   * Файлы портфолио, загруженные из публичной анкеты.
   */
  portfolioFiles?: (number | Media)[] | null;
  sourceType?:
    ('modal' | 'championship' | 'event' | 'opportunity' | 'find-team' | 'home' | 'about' | 'activities' | 'api') | null;
  /**
   * ID сущности-источника публичного CTA, если доступно.
   */
  sourceId?: string | null;
  /**
   * Человекочитаемое название/контекст источника.
   */
  sourceContext?: string | null;
  /**
   * К какому чемпионату привязана заявка
   */
  tournamentId?: (number | null) | Tournament;
  /**
   * Ключевое направление, выбранное в анкете (строка из «Темы кейса» чемпионата на момент подачи).
   */
  championshipDirection?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Contact information displayed in the site footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  /**
   * Admin-only label to identify this settings entry.
   */
  label: string;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Operator details displayed in the Privacy Policy (personal data operator section).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operator-settings".
 */
export interface OperatorSetting {
  id: number;
  /**
   * Admin-only label to identify this settings entry.
   */
  label: string;
  /**
   * Full name of the operator (for self-employed: full name; for legal entities: company name).
   */
  operatorName?: string | null;
  /**
   * Taxpayer Identification Number (ИНН).
   */
  operatorInn?: string | null;
  /**
   * Primary State Registration Number. Not required for self-employed individuals.
   */
  operatorOgrn?: string | null;
  /**
   * Legal and postal address for sending written requests from data subjects.
   */
  operatorAddress?: string | null;
  /**
   * Registration number in the Roskomnadzor personal data operators register (assigned after submitting the notification).
   */
  operatorRegistryNumber?: string | null;
  /**
   * Date of entry in the Roskomnadzor register (assigned after submitting the notification).
   */
  operatorRegistryDate?: string | null;
  /**
   * Email address where data subjects can send requests regarding their personal data.
   */
  contactsEmail?: string | null;
  /**
   * Postal address for submitting written requests from data subjects.
   */
  contactsPostalAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: string;
  collection: string;
  documentId: string;
  actorId?: string | null;
  actorEmail?: string | null;
  changedFields?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  summary: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Русские тексты статичных страниц. Карточки, события, FAQ и формы редактируются в своих коллекциях. Для иерархического просмотра используйте «Дерево текстов» в боковом меню.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-texts".
 */
export interface PageText {
  id: number;
  /**
   * Служебный ID. Не редактировать.
   */
  legacyId?: string | null;
  /**
   * Порядок в списке CMS.
   */
  sortOrder?: number | null;
  isPublished?: boolean | null;
  page: 'global' | 'home' | 'about' | 'championship' | 'activities' | 'find-team' | 'legal';
  /**
   * Нужен сайту, чтобы подставить текст в правильное место. Не редактировать.
   */
  translationKey: string;
  /**
   * Имя блока внутри страницы (на русском). Используется для группировки текстов в дереве редактирования.
   */
  blockName?: string | null;
  /**
   * Подсказка для поиска нужной строки.
   */
  label?: string | null;
  value?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Изображения страниц сайта. Управляются через «Дерево медиа» в боковом меню.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-media-slots".
 */
export interface PageMediaSlot {
  id: number;
  /**
   * Служебный идентификатор места на сайте. Не редактировать.
   */
  slotKey: string;
  page?: ('global' | 'home' | 'about' | 'championship' | 'activities' | 'find-team' | 'legal') | null;
  blockName?: string | null;
  /**
   * Человеческое описание места на сайте.
   */
  label?: string | null;
  /**
   * Загруженное изображение, которое заменит стандартное.
   */
  image?: (number | null) | Media;
  /**
   * Если включено — на сайте в этом месте не будет изображения.
   */
  hidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-generated localized copies for public CMS content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-localizations".
 */
export interface ContentLocalization {
  id: number;
  sourceCollection:
    'team-members' | 'activities' | 'events' | 'experts' | 'faqs' | 'opportunities' | 'tournaments' | 'page-texts';
  sourceId: string;
  language: 'ru' | 'en' | 'kk' | 'uz' | 'ar' | 'de' | 'es' | 'tr';
  localizedData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  translationStatus: 'pending' | 'in_progress' | 'ready' | 'failed';
  contentHash?: string | null;
  errorMessage?: string | null;
  generatedAt?: string | null;
  attempts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'experts';
        value: number | Expert;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'contact-settings';
        value: number | ContactSetting;
      } | null)
    | ({
        relationTo: 'operator-settings';
        value: number | OperatorSetting;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'page-texts';
        value: number | PageText;
      } | null)
    | ({
        relationTo: 'page-media-slots';
        value: number | PageMediaSlot;
      } | null)
    | ({
        relationTo: 'content-localizations';
        value: number | ContentLocalization;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  accountStatus?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  page?: T;
  blockName?: T;
  sortOrder?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  isFeatured?: T;
  isPublished?: T;
  originalLanguage?: T;
  sortOrder?: T;
  title?: T;
  pitch?: T;
  registrationStatus?: T;
  registrationDeadline?: T;
  heroImage?: T;
  slug?: T;
  date?: T;
  format?: T;
  ageLimit?: T;
  language?: T;
  teamsAllowed?: T;
  maxParticipants?: T;
  aboutHeading?: T;
  description?: T;
  aboutImage?: T;
  themesText?: T;
  evaluationCriteriaText?: T;
  expectedResult?: T;
  coverImage?: T;
  suitableFor?: T;
  type?: T;
  juryMembers?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  mentors?:
    | T
    | {
        value?: T;
        id?: T;
      };
  targetAudience?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  title?: T;
  shortDescription?: T;
  fullDescription?: T;
  imageUrl?: T;
  category?: T;
  status?: T;
  format?: T;
  date?: T;
  who?: T;
  benefits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  prerequisites?: T;
  ctaText?: T;
  ctaLink?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts_select".
 */
export interface ExpertsSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  name?: T;
  type?: T;
  role?: T;
  tournamentId?: T;
  expertise?: T;
  description?: T;
  photo?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  sortOrder?: T;
  isPublished?: T;
  originalLanguage?: T;
  page?: T;
  question?: T;
  answer?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  isPublished?: T;
  originalLanguage?: T;
  sortOrder?: T;
  title?: T;
  eventType?: T;
  format?: T;
  shortDescription?: T;
  image?: T;
  imageUrl?: T;
  slug?: T;
  eventDate?: T;
  showTime?: T;
  displayDate?: T;
  country?: T;
  venue?: T;
  onlineLink?: T;
  registrationDeadline?: T;
  participantLimit?: T;
  registrationUrl?: T;
  timeZone?: T;
  fullDescription?: T;
  audience?: T;
  outcomesText?: T;
  prerequisites?: T;
  speaker?: T;
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        value?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  isPublished?: T;
  originalLanguage?: T;
  sortOrder?: T;
  title?: T;
  organization?: T;
  category?: T;
  direction?: T;
  shortDescription?: T;
  image?: T;
  imageUrl?: T;
  logoUrl?: T;
  source?: T;
  editorPick?: T;
  recommended?: T;
  deadline?: T;
  startDate?: T;
  registrationOpen?: T;
  format?: T;
  participation?: T;
  cost?: T;
  country?: T;
  city?: T;
  ageMin?: T;
  ageMax?: T;
  finalDeadline?: T;
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  grades?:
    | T
    | {
        value?: T;
        id?: T;
      };
  fullDescription?: T;
  skills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        value?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        value?: T;
        id?: T;
      };
  officialUrl?: T;
  slug?: T;
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  portfolioValue?: T;
  savedCount?: T;
  publishedAt?: T;
  opportunityType?: T;
  seats?: T;
  funding?: T;
  internalApplicationsEnabled?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  sortOrder?: T;
  originalLanguage?: T;
  name?: T;
  email?: T;
  age?: T;
  country?: T;
  city?: T;
  shortBio?: T;
  interests?:
    | T
    | {
        value?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  targetRoles?: T;
  targetProject?: T;
  whyLooking?: T;
  contact?: T;
  contactType?: T;
  privacyConsent?: T;
  moderationStatus?: T;
  moderationComment?: T;
  reviewedAt?: T;
  isApproved?: T;
  portfolioLink?: T;
  portfolioFiles?: T;
  sourceType?: T;
  sourceId?: T;
  sourceContext?: T;
  tournamentId?: T;
  championshipDirection?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  label?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operator-settings_select".
 */
export interface OperatorSettingsSelect<T extends boolean = true> {
  label?: T;
  operatorName?: T;
  operatorInn?: T;
  operatorOgrn?: T;
  operatorAddress?: T;
  operatorRegistryNumber?: T;
  operatorRegistryDate?: T;
  contactsEmail?: T;
  contactsPostalAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collection?: T;
  documentId?: T;
  actorId?: T;
  actorEmail?: T;
  changedFields?:
    | T
    | {
        value?: T;
        id?: T;
      };
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-texts_select".
 */
export interface PageTextsSelect<T extends boolean = true> {
  legacyId?: T;
  sortOrder?: T;
  isPublished?: T;
  page?: T;
  translationKey?: T;
  blockName?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-media-slots_select".
 */
export interface PageMediaSlotsSelect<T extends boolean = true> {
  slotKey?: T;
  page?: T;
  blockName?: T;
  label?: T;
  image?: T;
  hidden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-localizations_select".
 */
export interface ContentLocalizationsSelect<T extends boolean = true> {
  sourceCollection?: T;
  sourceId?: T;
  language?: T;
  localizedData?: T;
  translationStatus?: T;
  contentHash?: T;
  errorMessage?: T;
  generatedAt?: T;
  attempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}