import type { CollectionConfig } from 'payload';

import { adminOrModerator, isAdmin, isModerator } from '../access';

export const Applications: CollectionConfig = {
  slug: 'applications',
  admin: {
    useAsTitle: 'name',
    group: 'Submissions',
  },
  access: {
    read: adminOrModerator,
    create: () => true,
    update: adminOrModerator,
    delete: adminOrModerator,
  },
  fields: [
    { name: 'ticketId', type: 'text', required: true, index: true },
    { name: 'user', type: 'relationship', relationTo: 'users' },
    {
      name: 'itemType',
      type: 'select',
      defaultValue: 'championship',
      options: ['championship', 'event', 'opportunity', 'program', 'team-post'],
      index: true,
    },
    { name: 'itemId', type: 'text', index: true },
    { name: 'itemTitle', type: 'text' },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'draft',
      options: [
        'draft',
        'submitted',
        'under_review',
        'clarification_required',
        'approved',
        'rejected',
        'cancelled',
        'new',
        'confirmed',
        'contacted',
      ],
      index: true,
      required: true,
    },
    { name: 'name', type: 'text', required: true },
    { name: 'email', type: 'email', required: true },
    { name: 'grade', type: 'text' },
    { name: 'age', type: 'text' },
    { name: 'city', type: 'text' },
    { name: 'contact', type: 'text' },
    { name: 'interest', type: 'text' },
    { name: 'tournamentId', type: 'text' },
    { name: 'hasTeam', type: 'text' },
    { name: 'teamSize', type: 'text' },
    { name: 'portfolioLink', type: 'text' },
    { name: 'coverLetter', type: 'textarea' },
    { name: 'customAnswers', type: 'json' },
    { name: 'adminComment', type: 'textarea' },
    {
      name: 'internalNotes',
      type: 'textarea',
      access: {
        read: ({ req: { user } }) => isAdmin(user) || isModerator(user),
        update: ({ req: { user } }) => isAdmin(user) || isModerator(user),
      },
    },
    { name: 'submittedAt', type: 'text' },
    { name: 'cancelledAt', type: 'text' },
    {
      name: 'attachments',
      type: 'relationship',
      relationTo: 'media',
      hasMany: true,
    },
    {
      name: 'source',
      type: 'select',
      defaultValue: 'modal',
      options: ['modal', 'inline', 'championship', 'find-team', 'api'],
    },
  ],
};
