/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const users_interests = sqliteTable(
  "users_interests",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("users_interests_order_idx").on(columns._order),
    index("users_interests_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_interests_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users_skills = sqliteTable(
  "users_skills",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("users_skills_order_idx").on(columns._order),
    index("users_skills_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_skills_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users_languages = sqliteTable(
  "users_languages",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("users_languages_order_idx").on(columns._order),
    index("users_languages_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_languages_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users_social_links = sqliteTable(
  "users_social_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("users_social_links_order_idx").on(columns._order),
    index("users_social_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_social_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users_sessions = sqliteTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    firstName: text("first_name"),
    lastName: text("last_name"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    avatarUrl: text("avatar_url"),
    avatarAlt: text("avatar_alt"),
    avatarPositionX: numeric("avatar_position_x", { mode: "number" }).default(
      50,
    ),
    avatarPositionY: numeric("avatar_position_y", { mode: "number" }).default(
      50,
    ),
    avatarScale: numeric("avatar_scale", { mode: "number" }).default(1),
    biography: text("biography"),
    portfolio: text("portfolio"),
    country: text("country"),
    city: text("city"),
    dateOfBirth: text("date_of_birth"),
    ageGroup: text("age_group"),
    school: text("school"),
    schoolGrade: text("school_grade"),
    preferredLanguage: text("preferred_language", {
      enum: ["ru", "en", "kk", "uz", "ar", "de", "es", "tr"],
    }),
    preferredLanguageMode: text("preferred_language_mode", {
      enum: ["auto", "manual"],
    }).default("auto"),
    teamSearchAvailable: integer("team_search_available", {
      mode: "boolean",
    }).default(false),
    publicProfile: integer("public_profile", { mode: "boolean" }).default(
      false,
    ),
    privacy_showCity: integer("privacy_show_city", { mode: "boolean" }).default(
      true,
    ),
    privacy_showSchool: integer("privacy_show_school", {
      mode: "boolean",
    }).default(false),
    privacy_showAge: integer("privacy_show_age", { mode: "boolean" }).default(
      true,
    ),
    privacy_showEmail: integer("privacy_show_email", {
      mode: "boolean",
    }).default(false),
    privacy_showSocialLinks: integer("privacy_show_social_links", {
      mode: "boolean",
    }).default(true),
    accountStatus: text("account_status", {
      enum: ["active", "blocked", "pending"],
    })
      .notNull()
      .default("active"),
    emailVerified: integer("email_verified", { mode: "boolean" }).default(
      false,
    ),
    verificationCode: text("verification_code"),
    verificationCodeExpires: text("verification_code_expires"),
    role: text("role", { enum: ["user", "moderator", "admin"] })
      .notNull()
      .default("user"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("users_avatar_idx").on(columns.avatar),
    index("users_country_idx").on(columns.country),
    index("users_city_idx").on(columns.city),
    index("users_age_group_idx").on(columns.ageGroup),
    index("users_school_grade_idx").on(columns.schoolGrade),
    index("users_team_search_available_idx").on(columns.teamSearchAvailable),
    index("users_public_profile_idx").on(columns.publicProfile),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = sqliteTable(
  "media",
  {
    id: integer("id").primaryKey(),
    alt: text("alt").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text("url"),
    thumbnailURL: text("thumbnail_u_r_l"),
    filename: text("filename"),
    mimeType: text("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const tournaments_skills = sqliteTable(
  "tournaments_skills",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("tournaments_skills_order_idx").on(columns._order),
    index("tournaments_skills_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tournaments.id],
      name: "tournaments_skills_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tournaments_mentors = sqliteTable(
  "tournaments_mentors",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("tournaments_mentors_order_idx").on(columns._order),
    index("tournaments_mentors_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tournaments.id],
      name: "tournaments_mentors_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tournaments = sqliteTable(
  "tournaments",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    isFeatured: integer("is_featured", { mode: "boolean" }).default(false),
    title: text("title").notNull(),
    type: text("type").notNull(),
    description: text("description").notNull(),
    date: text("date").notNull(),
    registrationDeadline: text("registration_deadline").notNull(),
    maxParticipants: numeric("max_participants", { mode: "number" }).notNull(),
    suitableFor: text("suitable_for"),
    format: text("format"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("tournaments_legacy_id_idx").on(columns.legacyId),
    index("tournaments_updated_at_idx").on(columns.updatedAt),
    index("tournaments_created_at_idx").on(columns.createdAt),
  ],
);

export const activities_benefits = sqliteTable(
  "activities_benefits",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("activities_benefits_order_idx").on(columns._order),
    index("activities_benefits_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [activities.id],
      name: "activities_benefits_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const activities = sqliteTable(
  "activities",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    title: text("title").notNull(),
    shortDescription: text("short_description").notNull(),
    fullDescription: text("full_description").notNull(),
    format: text("format").notNull(),
    date: text("date").notNull(),
    imageUrl: text("image_url").notNull(),
    category: text("category", {
      enum: [
        "educational",
        "project",
        "social",
        "online-meeting",
        "workshop",
        "team",
      ],
    }).notNull(),
    status: text("status", {
      enum: ["coming", "ongoing", "completed"],
    }).notNull(),
    who: text("who").notNull(),
    prerequisites: text("prerequisites").notNull(),
    ctaText: text("cta_text").notNull(),
    ctaLink: text("cta_link"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("activities_legacy_id_idx").on(columns.legacyId),
    index("activities_updated_at_idx").on(columns.updatedAt),
    index("activities_created_at_idx").on(columns.createdAt),
  ],
);

export const experts = sqliteTable(
  "experts",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    name: text("name").notNull(),
    type: text("type", { enum: ["jury", "mentor", "expert"] })
      .notNull()
      .default("expert"),
    role: text("role").notNull(),
    expertise: text("expertise").notNull(),
    description: text("description").notNull(),
    photo: integer("photo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    tournamentId: integer("tournament_id_id").references(() => tournaments.id, {
      onDelete: "set null",
    }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("experts_legacy_id_idx").on(columns.legacyId),
    index("experts_photo_idx").on(columns.photo),
    index("experts_tournament_id_idx").on(columns.tournamentId),
    index("experts_updated_at_idx").on(columns.updatedAt),
    index("experts_created_at_idx").on(columns.createdAt),
  ],
);

export const faqs = sqliteTable(
  "faqs",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    page: text("page", {
      enum: [
        "home",
        "about",
        "championship",
        "activities",
        "find-team",
        "opportunities",
      ],
    }).notNull(),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("faqs_legacy_id_idx").on(columns.legacyId),
    index("faqs_page_idx").on(columns.page),
    index("faqs_updated_at_idx").on(columns.updatedAt),
    index("faqs_created_at_idx").on(columns.createdAt),
  ],
);

export const events_languages = sqliteTable(
  "events_languages",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("events_languages_order_idx").on(columns._order),
    index("events_languages_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [events.id],
      name: "events_languages_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const events_materials = sqliteTable(
  "events_materials",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("events_materials_order_idx").on(columns._order),
    index("events_materials_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [events.id],
      name: "events_materials_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const events = sqliteTable(
  "events",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    shortDescription: text("short_description").notNull(),
    fullDescription: text("full_description"),
    imageUrl: text("image_url"),
    eventType: text("event_type").notNull(),
    eventDate: text("event_date")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    timeZone: text("time_zone").default("UTC"),
    registrationDeadline: text("registration_deadline").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    participantLimit: numeric("participant_limit", { mode: "number" }),
    format: text("format", { enum: ["online", "offline", "hybrid"] }).notNull(),
    country: text("country"),
    venue: text("venue"),
    onlineLink: text("online_link"),
    speaker: text("speaker"),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("events_legacy_id_idx").on(columns.legacyId),
    uniqueIndex("events_slug_idx").on(columns.slug),
    index("events_event_type_idx").on(columns.eventType),
    index("events_event_date_idx").on(columns.eventDate),
    index("events_registration_deadline_idx").on(columns.registrationDeadline),
    index("events_format_idx").on(columns.format),
    index("events_country_idx").on(columns.country),
    index("events_updated_at_idx").on(columns.updatedAt),
    index("events_created_at_idx").on(columns.createdAt),
  ],
);

export const opportunities_languages = sqliteTable(
  "opportunities_languages",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("opportunities_languages_order_idx").on(columns._order),
    index("opportunities_languages_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [opportunities.id],
      name: "opportunities_languages_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const opportunities_requirements = sqliteTable(
  "opportunities_requirements",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("opportunities_requirements_order_idx").on(columns._order),
    index("opportunities_requirements_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [opportunities.id],
      name: "opportunities_requirements_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const opportunities_benefits = sqliteTable(
  "opportunities_benefits",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("opportunities_benefits_order_idx").on(columns._order),
    index("opportunities_benefits_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [opportunities.id],
      name: "opportunities_benefits_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const opportunities_documents = sqliteTable(
  "opportunities_documents",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("opportunities_documents_order_idx").on(columns._order),
    index("opportunities_documents_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [opportunities.id],
      name: "opportunities_documents_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const opportunities = sqliteTable(
  "opportunities",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    organization: text("organization").notNull(),
    opportunityType: text("opportunity_type").notNull(),
    shortDescription: text("short_description").notNull(),
    fullDescription: text("full_description"),
    logoUrl: text("logo_url"),
    country: text("country"),
    format: text("format", { enum: ["online", "offline", "hybrid"] }),
    ageMin: numeric("age_min", { mode: "number" }),
    ageMax: numeric("age_max", { mode: "number" }),
    cost: text("cost"),
    funding: integer("funding", { mode: "boolean" }).default(false),
    deadline: text("deadline").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    officialUrl: text("official_url"),
    internalApplicationsEnabled: integer("internal_applications_enabled", {
      mode: "boolean",
    }).default(false),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("opportunities_legacy_id_idx").on(columns.legacyId),
    uniqueIndex("opportunities_slug_idx").on(columns.slug),
    index("opportunities_organization_idx").on(columns.organization),
    index("opportunities_opportunity_type_idx").on(columns.opportunityType),
    index("opportunities_country_idx").on(columns.country),
    index("opportunities_format_idx").on(columns.format),
    index("opportunities_funding_idx").on(columns.funding),
    index("opportunities_deadline_idx").on(columns.deadline),
    index("opportunities_updated_at_idx").on(columns.updatedAt),
    index("opportunities_created_at_idx").on(columns.createdAt),
  ],
);

export const team_members_interests = sqliteTable(
  "team_members_interests",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("team_members_interests_order_idx").on(columns._order),
    index("team_members_interests_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [team_members.id],
      name: "team_members_interests_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const team_members_skills = sqliteTable(
  "team_members_skills",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("team_members_skills_order_idx").on(columns._order),
    index("team_members_skills_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [team_members.id],
      name: "team_members_skills_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const team_members_target_roles = sqliteTable(
  "team_members_target_roles",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: text("value", {
      enum: [
        "developer",
        "designer",
        "researcher",
        "product_manager",
        "marketer",
        "team_lead",
        "analyst",
        "other",
      ],
    }),
    id: integer("id").primaryKey(),
  },
  (columns) => [
    index("team_members_target_roles_order_idx").on(columns.order),
    index("team_members_target_roles_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [team_members.id],
      name: "team_members_target_roles_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const team_members = sqliteTable(
  "team_members",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    name: text("name").notNull(),
    age: numeric("age", { mode: "number" }).notNull(),
    country: text("country").notNull(),
    city: text("city"),
    shortBio: text("short_bio").notNull(),
    targetProject: text("target_project"),
    whyLooking: text("why_looking").notNull(),
    contact: text("contact").notNull(),
    contactType: text("contact_type", {
      enum: ["telegram", "email", "discord"],
    }).notNull(),
    isApproved: integer("is_approved", { mode: "boolean" }).default(false),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("team_members_legacy_id_idx").on(columns.legacyId),
    index("team_members_updated_at_idx").on(columns.updatedAt),
    index("team_members_created_at_idx").on(columns.createdAt),
  ],
);

export const team_posts_required_skills = sqliteTable(
  "team_posts_required_skills",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("team_posts_required_skills_order_idx").on(columns._order),
    index("team_posts_required_skills_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [team_posts.id],
      name: "team_posts_required_skills_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const team_posts_own_skills = sqliteTable(
  "team_posts_own_skills",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("team_posts_own_skills_order_idx").on(columns._order),
    index("team_posts_own_skills_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [team_posts.id],
      name: "team_posts_own_skills_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const team_posts_interests = sqliteTable(
  "team_posts_interests",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("team_posts_interests_order_idx").on(columns._order),
    index("team_posts_interests_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [team_posts.id],
      name: "team_posts_interests_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const team_posts = sqliteTable(
  "team_posts",
  {
    id: integer("id").primaryKey(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    title: text("title").notNull(),
    description: text("description").notNull(),
    status: text("status", { enum: ["draft", "published", "hidden"] }).default(
      "draft",
    ),
    championshipId: text("championship_id"),
    projectName: text("project_name"),
    communicationLanguage: text("communication_language"),
    timeZone: text("time_zone"),
    workingFormat: text("working_format", {
      enum: ["online", "offline", "hybrid"],
    }),
    openPositions: numeric("open_positions", { mode: "number" }).default(1),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("team_posts_user_idx").on(columns.user),
    index("team_posts_status_idx").on(columns.status),
    index("team_posts_updated_at_idx").on(columns.updatedAt),
    index("team_posts_created_at_idx").on(columns.createdAt),
  ],
);

export const team_responses = sqliteTable(
  "team_responses",
  {
    id: integer("id").primaryKey(),
    post: integer("post_id")
      .notNull()
      .references(() => team_posts.id, {
        onDelete: "set null",
      }),
    sender: integer("sender_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    recipient: integer("recipient_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    kind: text("kind", { enum: ["response", "invitation"] }).default(
      "response",
    ),
    message: text("message").notNull(),
    status: text("status", {
      enum: ["pending", "accepted", "rejected"],
    }).default("pending"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("team_responses_post_idx").on(columns.post),
    index("team_responses_sender_idx").on(columns.sender),
    index("team_responses_recipient_idx").on(columns.recipient),
    index("team_responses_kind_idx").on(columns.kind),
    index("team_responses_status_idx").on(columns.status),
    index("team_responses_updated_at_idx").on(columns.updatedAt),
    index("team_responses_created_at_idx").on(columns.createdAt),
  ],
);

export const trust_points = sqliteTable(
  "trust_points",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    title: text("title").notNull(),
    description: text("description").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("trust_points_legacy_id_idx").on(columns.legacyId),
    index("trust_points_updated_at_idx").on(columns.updatedAt),
    index("trust_points_created_at_idx").on(columns.createdAt),
  ],
);

export const pillars = sqliteTable(
  "pillars",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    label: text("label").notNull(),
    title: text("title").notNull(),
    description: text("description").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("pillars_legacy_id_idx").on(columns.legacyId),
    index("pillars_updated_at_idx").on(columns.updatedAt),
    index("pillars_created_at_idx").on(columns.createdAt),
  ],
);

export const scenarios = sqliteTable(
  "scenarios",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    title: text("title").notNull(),
    who: text("who").notNull(),
    why: text("why").notNull(),
    ctaText: text("cta_text").notNull(),
    actionType: text("action_type", {
      enum: ["apply", "team", "activity", "general"],
    })
      .notNull()
      .default("general"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("scenarios_legacy_id_idx").on(columns.legacyId),
    index("scenarios_updated_at_idx").on(columns.updatedAt),
    index("scenarios_created_at_idx").on(columns.createdAt),
  ],
);

export const stats = sqliteTable(
  "stats",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isPublished: integer("is_published", { mode: "boolean" }).default(true),
    value: text("value").notNull(),
    label: text("label").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("stats_legacy_id_idx").on(columns.legacyId),
    index("stats_updated_at_idx").on(columns.updatedAt),
    index("stats_created_at_idx").on(columns.createdAt),
  ],
);

export const applications = sqliteTable(
  "applications",
  {
    id: integer("id").primaryKey(),
    ticketId: text("ticket_id").notNull(),
    user: integer("user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    itemType: text("item_type", {
      enum: ["championship", "event", "opportunity", "program", "team-post"],
    }).default("championship"),
    itemId: text("item_id"),
    itemTitle: text("item_title"),
    status: text("status", {
      enum: [
        "draft",
        "submitted",
        "under_review",
        "clarification_required",
        "approved",
        "rejected",
        "cancelled",
        "new",
        "confirmed",
        "contacted",
      ],
    })
      .notNull()
      .default("draft"),
    name: text("name").notNull(),
    email: text("email").notNull(),
    grade: text("grade"),
    age: text("age"),
    city: text("city"),
    contact: text("contact"),
    interest: text("interest"),
    tournamentId: text("tournament_id"),
    hasTeam: text("has_team"),
    teamSize: text("team_size"),
    portfolioLink: text("portfolio_link"),
    coverLetter: text("cover_letter"),
    customAnswers: text("custom_answers", { mode: "json" }),
    adminComment: text("admin_comment"),
    internalNotes: text("internal_notes"),
    submittedAt: text("submitted_at"),
    cancelledAt: text("cancelled_at"),
    source: text("source", {
      enum: ["modal", "inline", "championship", "find-team", "api"],
    }).default("modal"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("applications_ticket_id_idx").on(columns.ticketId),
    index("applications_user_idx").on(columns.user),
    index("applications_item_type_idx").on(columns.itemType),
    index("applications_item_id_idx").on(columns.itemId),
    index("applications_status_idx").on(columns.status),
    index("applications_updated_at_idx").on(columns.updatedAt),
    index("applications_created_at_idx").on(columns.createdAt),
  ],
);

export const applications_rels = sqliteTable(
  "applications_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("applications_rels_order_idx").on(columns.order),
    index("applications_rels_parent_idx").on(columns.parent),
    index("applications_rels_path_idx").on(columns.path),
    index("applications_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [applications.id],
      name: "applications_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "applications_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const application_status_history = sqliteTable(
  "application_status_history",
  {
    id: integer("id").primaryKey(),
    application: integer("application_id")
      .notNull()
      .references(() => applications.id, {
        onDelete: "set null",
      }),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    actor: integer("actor_id").references(() => users.id, {
      onDelete: "set null",
    }),
    previousStatus: text("previous_status"),
    status: text("status").notNull(),
    comment: text("comment"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("application_status_history_application_idx").on(columns.application),
    index("application_status_history_user_idx").on(columns.user),
    index("application_status_history_actor_idx").on(columns.actor),
    index("application_status_history_updated_at_idx").on(columns.updatedAt),
    index("application_status_history_created_at_idx").on(columns.createdAt),
  ],
);

export const favorites = sqliteTable(
  "favorites",
  {
    id: integer("id").primaryKey(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    itemType: text("item_type", {
      enum: [
        "championship",
        "event",
        "opportunity",
        "participant",
        "team-post",
      ],
    }).notNull(),
    itemId: text("item_id").notNull(),
    itemTitle: text("item_title").notNull(),
    href: text("href").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("favorites_user_idx").on(columns.user),
    index("favorites_item_type_idx").on(columns.itemType),
    index("favorites_item_id_idx").on(columns.itemId),
    index("favorites_updated_at_idx").on(columns.updatedAt),
    index("favorites_created_at_idx").on(columns.createdAt),
  ],
);

export const notifications = sqliteTable(
  "notifications",
  {
    id: integer("id").primaryKey(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    type: text("type", {
      enum: [
        "application_submitted",
        "application_status_changed",
        "clarification_requested",
        "team_response_received",
        "team_response_accepted",
        "team_response_rejected",
        "team_invitation_received",
        "upcoming_deadline",
        "upcoming_event",
        "announcement",
        "blog_post_submitted",
        "blog_post_pending_review",
        "blog_post_approved",
        "blog_post_published",
        "blog_post_rejected",
        "blog_post_needs_revision",
      ],
    }).notNull(),
    relatedType: text("related_type", {
      enum: [
        "application",
        "championship",
        "event",
        "opportunity",
        "participant",
        "team-post",
        "team-response",
        "blog-post",
      ],
    }),
    relatedId: text("related_id"),
    href: text("href"),
    data: text("data", { mode: "json" }),
    readAt: text("read_at"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("notifications_user_idx").on(columns.user),
    index("notifications_type_idx").on(columns.type),
    index("notifications_read_at_idx").on(columns.readAt),
    index("notifications_updated_at_idx").on(columns.updatedAt),
    index("notifications_created_at_idx").on(columns.createdAt),
  ],
);

export const community_leads = sqliteTable(
  "community_leads",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    age: text("age").notNull(),
    location: text("location").notNull(),
    contact: text("contact").notNull(),
    interest: text("interest"),
    source: text("source").default("home-inline"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("community_leads_updated_at_idx").on(columns.updatedAt),
    index("community_leads_created_at_idx").on(columns.createdAt),
  ],
);

export const contact_settings = sqliteTable(
  "contact_settings",
  {
    id: integer("id").primaryKey(),
    label: text("label").notNull().default("Site Contacts"),
    email: text("email").default("info@navykus.org"),
    phone: text("phone").default("+7 (999) 000-00-00"),
    telegram: text("telegram").default("@navykus_com"),
    address: text("address").default(""),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("contact_settings_updated_at_idx").on(columns.updatedAt),
    index("contact_settings_created_at_idx").on(columns.createdAt),
  ],
);

export const blog_posts_tags = sqliteTable(
  "blog_posts_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    value: text("value").notNull(),
  },
  (columns) => [
    index("blog_posts_tags_order_idx").on(columns._order),
    index("blog_posts_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [blog_posts.id],
      name: "blog_posts_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const blog_posts = sqliteTable(
  "blog_posts",
  {
    id: integer("id").primaryKey(),
    legacyId: text("legacy_id"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    title: text("title").notNull(),
    excerpt: text("excerpt").notNull(),
    content: text("content").notNull(),
    cover: integer("cover_id").references(() => media.id, {
      onDelete: "set null",
    }),
    coverAlt: text("cover_alt"),
    category: text("category", {
      enum: [
        "news",
        "championships",
        "activities",
        "opportunities",
        "stories",
        "interviews",
        "tips",
        "education",
        "projects",
      ],
    }).notNull(),
    status: text("status", {
      enum: [
        "draft",
        "pending_review",
        "needs_revision",
        "approved",
        "published",
        "rejected",
        "archived",
      ],
    })
      .notNull()
      .default("draft"),
    author: integer("author_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    originalLanguage: text("original_language", {
      enum: ["ru", "en", "kk", "uz", "ar", "de", "es", "tr"],
    })
      .notNull()
      .default("ru"),
    slug: text("slug").notNull(),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    readingTime: numeric("reading_time", { mode: "number" }),
    views: numeric("views", { mode: "number" }).default(0),
    likes: numeric("likes", { mode: "number" }).default(0),
    publishedAt: text("published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    moderationComment: text("moderation_comment"),
    isApproved: integer("is_approved", { mode: "boolean" }).default(false),
    isPublished: integer("is_published", { mode: "boolean" }).default(false),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("blog_posts_legacy_id_idx").on(columns.legacyId),
    index("blog_posts_cover_idx").on(columns.cover),
    index("blog_posts_category_idx").on(columns.category),
    index("blog_posts_status_idx").on(columns.status),
    index("blog_posts_author_idx").on(columns.author),
    index("blog_posts_original_language_idx").on(columns.originalLanguage),
    uniqueIndex("blog_posts_slug_idx").on(columns.slug),
    index("blog_posts_updated_at_idx").on(columns.updatedAt),
    index("blog_posts_created_at_idx").on(columns.createdAt),
  ],
);

export const blog_post_localizations = sqliteTable(
  "blog_post_localizations",
  {
    id: integer("id").primaryKey(),
    post: integer("post_id")
      .notNull()
      .references(() => blog_posts.id, {
        onDelete: "set null",
      }),
    language: text("language", {
      enum: ["ru", "en", "kk", "uz", "ar", "de", "es", "tr"],
    }).notNull(),
    title: text("title").notNull(),
    excerpt: text("excerpt").notNull(),
    content: text("content").notNull(),
    slug: text("slug").notNull(),
    coverAlt: text("cover_alt"),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    translationStatus: text("translation_status", {
      enum: ["pending", "in_progress", "ready", "failed"],
    })
      .notNull()
      .default("pending"),
    errorMessage: text("error_message"),
    generatedAt: text("generated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    attempts: numeric("attempts", { mode: "number" }).default(0),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("blog_post_localizations_post_idx").on(columns.post),
    index("blog_post_localizations_language_idx").on(columns.language),
    index("blog_post_localizations_slug_idx").on(columns.slug),
    index("blog_post_localizations_translation_status_idx").on(
      columns.translationStatus,
    ),
    index("blog_post_localizations_updated_at_idx").on(columns.updatedAt),
    index("blog_post_localizations_created_at_idx").on(columns.createdAt),
  ],
);

export const blog_moderation_history = sqliteTable(
  "blog_moderation_history",
  {
    id: integer("id").primaryKey(),
    post: integer("post_id")
      .notNull()
      .references(() => blog_posts.id, {
        onDelete: "set null",
      }),
    author: integer("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    actor: integer("actor_id").references(() => users.id, {
      onDelete: "set null",
    }),
    previousStatus: text("previous_status"),
    status: text("status").notNull(),
    comment: text("comment"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("blog_moderation_history_post_idx").on(columns.post),
    index("blog_moderation_history_author_idx").on(columns.author),
    index("blog_moderation_history_actor_idx").on(columns.actor),
    index("blog_moderation_history_updated_at_idx").on(columns.updatedAt),
    index("blog_moderation_history_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    tournamentsID: integer("tournaments_id"),
    activitiesID: integer("activities_id"),
    expertsID: integer("experts_id"),
    faqsID: integer("faqs_id"),
    eventsID: integer("events_id"),
    opportunitiesID: integer("opportunities_id"),
    "team-membersID": integer("team_members_id"),
    "team-postsID": integer("team_posts_id"),
    "team-responsesID": integer("team_responses_id"),
    "trust-pointsID": integer("trust_points_id"),
    pillarsID: integer("pillars_id"),
    scenariosID: integer("scenarios_id"),
    statsID: integer("stats_id"),
    applicationsID: integer("applications_id"),
    "application-status-historyID": integer("application_status_history_id"),
    favoritesID: integer("favorites_id"),
    notificationsID: integer("notifications_id"),
    "community-leadsID": integer("community_leads_id"),
    "contact-settingsID": integer("contact_settings_id"),
    "blog-postsID": integer("blog_posts_id"),
    "blog-post-localizationsID": integer("blog_post_localizations_id"),
    "blog-moderation-historyID": integer("blog_moderation_history_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_tournaments_id_idx").on(
      columns.tournamentsID,
    ),
    index("payload_locked_documents_rels_activities_id_idx").on(
      columns.activitiesID,
    ),
    index("payload_locked_documents_rels_experts_id_idx").on(columns.expertsID),
    index("payload_locked_documents_rels_faqs_id_idx").on(columns.faqsID),
    index("payload_locked_documents_rels_events_id_idx").on(columns.eventsID),
    index("payload_locked_documents_rels_opportunities_id_idx").on(
      columns.opportunitiesID,
    ),
    index("payload_locked_documents_rels_team_members_id_idx").on(
      columns["team-membersID"],
    ),
    index("payload_locked_documents_rels_team_posts_id_idx").on(
      columns["team-postsID"],
    ),
    index("payload_locked_documents_rels_team_responses_id_idx").on(
      columns["team-responsesID"],
    ),
    index("payload_locked_documents_rels_trust_points_id_idx").on(
      columns["trust-pointsID"],
    ),
    index("payload_locked_documents_rels_pillars_id_idx").on(columns.pillarsID),
    index("payload_locked_documents_rels_scenarios_id_idx").on(
      columns.scenariosID,
    ),
    index("payload_locked_documents_rels_stats_id_idx").on(columns.statsID),
    index("payload_locked_documents_rels_applications_id_idx").on(
      columns.applicationsID,
    ),
    index("payload_locked_documents_rels_application_status_history_idx").on(
      columns["application-status-historyID"],
    ),
    index("payload_locked_documents_rels_favorites_id_idx").on(
      columns.favoritesID,
    ),
    index("payload_locked_documents_rels_notifications_id_idx").on(
      columns.notificationsID,
    ),
    index("payload_locked_documents_rels_community_leads_id_idx").on(
      columns["community-leadsID"],
    ),
    index("payload_locked_documents_rels_contact_settings_id_idx").on(
      columns["contact-settingsID"],
    ),
    index("payload_locked_documents_rels_blog_posts_id_idx").on(
      columns["blog-postsID"],
    ),
    index("payload_locked_documents_rels_blog_post_localizations_id_idx").on(
      columns["blog-post-localizationsID"],
    ),
    index("payload_locked_documents_rels_blog_moderation_history_id_idx").on(
      columns["blog-moderation-historyID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tournamentsID"]],
      foreignColumns: [tournaments.id],
      name: "payload_locked_documents_rels_tournaments_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["activitiesID"]],
      foreignColumns: [activities.id],
      name: "payload_locked_documents_rels_activities_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["expertsID"]],
      foreignColumns: [experts.id],
      name: "payload_locked_documents_rels_experts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["faqsID"]],
      foreignColumns: [faqs.id],
      name: "payload_locked_documents_rels_faqs_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["eventsID"]],
      foreignColumns: [events.id],
      name: "payload_locked_documents_rels_events_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["opportunitiesID"]],
      foreignColumns: [opportunities.id],
      name: "payload_locked_documents_rels_opportunities_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["team-membersID"]],
      foreignColumns: [team_members.id],
      name: "payload_locked_documents_rels_team_members_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["team-postsID"]],
      foreignColumns: [team_posts.id],
      name: "payload_locked_documents_rels_team_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["team-responsesID"]],
      foreignColumns: [team_responses.id],
      name: "payload_locked_documents_rels_team_responses_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["trust-pointsID"]],
      foreignColumns: [trust_points.id],
      name: "payload_locked_documents_rels_trust_points_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pillarsID"]],
      foreignColumns: [pillars.id],
      name: "payload_locked_documents_rels_pillars_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["scenariosID"]],
      foreignColumns: [scenarios.id],
      name: "payload_locked_documents_rels_scenarios_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["statsID"]],
      foreignColumns: [stats.id],
      name: "payload_locked_documents_rels_stats_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["applicationsID"]],
      foreignColumns: [applications.id],
      name: "payload_locked_documents_rels_applications_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["application-status-historyID"]],
      foreignColumns: [application_status_history.id],
      name: "payload_locked_documents_rels_application_status_history_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["favoritesID"]],
      foreignColumns: [favorites.id],
      name: "payload_locked_documents_rels_favorites_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["notificationsID"]],
      foreignColumns: [notifications.id],
      name: "payload_locked_documents_rels_notifications_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["community-leadsID"]],
      foreignColumns: [community_leads.id],
      name: "payload_locked_documents_rels_community_leads_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["contact-settingsID"]],
      foreignColumns: [contact_settings.id],
      name: "payload_locked_documents_rels_contact_settings_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blog-postsID"]],
      foreignColumns: [blog_posts.id],
      name: "payload_locked_documents_rels_blog_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blog-post-localizationsID"]],
      foreignColumns: [blog_post_localizations.id],
      name: "payload_locked_documents_rels_blog_post_localizations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blog-moderation-historyID"]],
      foreignColumns: [blog_moderation_history.id],
      name: "payload_locked_documents_rels_blog_moderation_history_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_interests = relations(
  users_interests,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_interests._parentID],
      references: [users.id],
      relationName: "interests",
    }),
  }),
);
export const relations_users_skills = relations(users_skills, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_skills._parentID],
    references: [users.id],
    relationName: "skills",
  }),
}));
export const relations_users_languages = relations(
  users_languages,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_languages._parentID],
      references: [users.id],
      relationName: "languages",
    }),
  }),
);
export const relations_users_social_links = relations(
  users_social_links,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_social_links._parentID],
      references: [users.id],
      relationName: "socialLinks",
    }),
  }),
);
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  interests: many(users_interests, {
    relationName: "interests",
  }),
  skills: many(users_skills, {
    relationName: "skills",
  }),
  languages: many(users_languages, {
    relationName: "languages",
  }),
  socialLinks: many(users_social_links, {
    relationName: "socialLinks",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_tournaments_skills = relations(
  tournaments_skills,
  ({ one }) => ({
    _parentID: one(tournaments, {
      fields: [tournaments_skills._parentID],
      references: [tournaments.id],
      relationName: "skills",
    }),
  }),
);
export const relations_tournaments_mentors = relations(
  tournaments_mentors,
  ({ one }) => ({
    _parentID: one(tournaments, {
      fields: [tournaments_mentors._parentID],
      references: [tournaments.id],
      relationName: "mentors",
    }),
  }),
);
export const relations_tournaments = relations(tournaments, ({ many }) => ({
  skills: many(tournaments_skills, {
    relationName: "skills",
  }),
  mentors: many(tournaments_mentors, {
    relationName: "mentors",
  }),
}));
export const relations_activities_benefits = relations(
  activities_benefits,
  ({ one }) => ({
    _parentID: one(activities, {
      fields: [activities_benefits._parentID],
      references: [activities.id],
      relationName: "benefits",
    }),
  }),
);
export const relations_activities = relations(activities, ({ many }) => ({
  benefits: many(activities_benefits, {
    relationName: "benefits",
  }),
}));
export const relations_experts = relations(experts, ({ one }) => ({
  photo: one(media, {
    fields: [experts.photo],
    references: [media.id],
    relationName: "photo",
  }),
  tournamentId: one(tournaments, {
    fields: [experts.tournamentId],
    references: [tournaments.id],
    relationName: "tournamentId",
  }),
}));
export const relations_faqs = relations(faqs, () => ({}));
export const relations_events_languages = relations(
  events_languages,
  ({ one }) => ({
    _parentID: one(events, {
      fields: [events_languages._parentID],
      references: [events.id],
      relationName: "languages",
    }),
  }),
);
export const relations_events_materials = relations(
  events_materials,
  ({ one }) => ({
    _parentID: one(events, {
      fields: [events_materials._parentID],
      references: [events.id],
      relationName: "materials",
    }),
  }),
);
export const relations_events = relations(events, ({ many }) => ({
  languages: many(events_languages, {
    relationName: "languages",
  }),
  materials: many(events_materials, {
    relationName: "materials",
  }),
}));
export const relations_opportunities_languages = relations(
  opportunities_languages,
  ({ one }) => ({
    _parentID: one(opportunities, {
      fields: [opportunities_languages._parentID],
      references: [opportunities.id],
      relationName: "languages",
    }),
  }),
);
export const relations_opportunities_requirements = relations(
  opportunities_requirements,
  ({ one }) => ({
    _parentID: one(opportunities, {
      fields: [opportunities_requirements._parentID],
      references: [opportunities.id],
      relationName: "requirements",
    }),
  }),
);
export const relations_opportunities_benefits = relations(
  opportunities_benefits,
  ({ one }) => ({
    _parentID: one(opportunities, {
      fields: [opportunities_benefits._parentID],
      references: [opportunities.id],
      relationName: "benefits",
    }),
  }),
);
export const relations_opportunities_documents = relations(
  opportunities_documents,
  ({ one }) => ({
    _parentID: one(opportunities, {
      fields: [opportunities_documents._parentID],
      references: [opportunities.id],
      relationName: "documents",
    }),
  }),
);
export const relations_opportunities = relations(opportunities, ({ many }) => ({
  languages: many(opportunities_languages, {
    relationName: "languages",
  }),
  requirements: many(opportunities_requirements, {
    relationName: "requirements",
  }),
  benefits: many(opportunities_benefits, {
    relationName: "benefits",
  }),
  documents: many(opportunities_documents, {
    relationName: "documents",
  }),
}));
export const relations_team_members_interests = relations(
  team_members_interests,
  ({ one }) => ({
    _parentID: one(team_members, {
      fields: [team_members_interests._parentID],
      references: [team_members.id],
      relationName: "interests",
    }),
  }),
);
export const relations_team_members_skills = relations(
  team_members_skills,
  ({ one }) => ({
    _parentID: one(team_members, {
      fields: [team_members_skills._parentID],
      references: [team_members.id],
      relationName: "skills",
    }),
  }),
);
export const relations_team_members_target_roles = relations(
  team_members_target_roles,
  ({ one }) => ({
    parent: one(team_members, {
      fields: [team_members_target_roles.parent],
      references: [team_members.id],
      relationName: "targetRoles",
    }),
  }),
);
export const relations_team_members = relations(team_members, ({ many }) => ({
  interests: many(team_members_interests, {
    relationName: "interests",
  }),
  skills: many(team_members_skills, {
    relationName: "skills",
  }),
  targetRoles: many(team_members_target_roles, {
    relationName: "targetRoles",
  }),
}));
export const relations_team_posts_required_skills = relations(
  team_posts_required_skills,
  ({ one }) => ({
    _parentID: one(team_posts, {
      fields: [team_posts_required_skills._parentID],
      references: [team_posts.id],
      relationName: "requiredSkills",
    }),
  }),
);
export const relations_team_posts_own_skills = relations(
  team_posts_own_skills,
  ({ one }) => ({
    _parentID: one(team_posts, {
      fields: [team_posts_own_skills._parentID],
      references: [team_posts.id],
      relationName: "ownSkills",
    }),
  }),
);
export const relations_team_posts_interests = relations(
  team_posts_interests,
  ({ one }) => ({
    _parentID: one(team_posts, {
      fields: [team_posts_interests._parentID],
      references: [team_posts.id],
      relationName: "interests",
    }),
  }),
);
export const relations_team_posts = relations(team_posts, ({ one, many }) => ({
  user: one(users, {
    fields: [team_posts.user],
    references: [users.id],
    relationName: "user",
  }),
  requiredSkills: many(team_posts_required_skills, {
    relationName: "requiredSkills",
  }),
  ownSkills: many(team_posts_own_skills, {
    relationName: "ownSkills",
  }),
  interests: many(team_posts_interests, {
    relationName: "interests",
  }),
}));
export const relations_team_responses = relations(
  team_responses,
  ({ one }) => ({
    post: one(team_posts, {
      fields: [team_responses.post],
      references: [team_posts.id],
      relationName: "post",
    }),
    sender: one(users, {
      fields: [team_responses.sender],
      references: [users.id],
      relationName: "sender",
    }),
    recipient: one(users, {
      fields: [team_responses.recipient],
      references: [users.id],
      relationName: "recipient",
    }),
  }),
);
export const relations_trust_points = relations(trust_points, () => ({}));
export const relations_pillars = relations(pillars, () => ({}));
export const relations_scenarios = relations(scenarios, () => ({}));
export const relations_stats = relations(stats, () => ({}));
export const relations_applications_rels = relations(
  applications_rels,
  ({ one }) => ({
    parent: one(applications, {
      fields: [applications_rels.parent],
      references: [applications.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [applications_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_applications = relations(
  applications,
  ({ one, many }) => ({
    user: one(users, {
      fields: [applications.user],
      references: [users.id],
      relationName: "user",
    }),
    _rels: many(applications_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_application_status_history = relations(
  application_status_history,
  ({ one }) => ({
    application: one(applications, {
      fields: [application_status_history.application],
      references: [applications.id],
      relationName: "application",
    }),
    user: one(users, {
      fields: [application_status_history.user],
      references: [users.id],
      relationName: "user",
    }),
    actor: one(users, {
      fields: [application_status_history.actor],
      references: [users.id],
      relationName: "actor",
    }),
  }),
);
export const relations_favorites = relations(favorites, ({ one }) => ({
  user: one(users, {
    fields: [favorites.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_notifications = relations(notifications, ({ one }) => ({
  user: one(users, {
    fields: [notifications.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_community_leads = relations(community_leads, () => ({}));
export const relations_contact_settings = relations(
  contact_settings,
  () => ({}),
);
export const relations_blog_posts_tags = relations(
  blog_posts_tags,
  ({ one }) => ({
    _parentID: one(blog_posts, {
      fields: [blog_posts_tags._parentID],
      references: [blog_posts.id],
      relationName: "tags",
    }),
  }),
);
export const relations_blog_posts = relations(blog_posts, ({ one, many }) => ({
  cover: one(media, {
    fields: [blog_posts.cover],
    references: [media.id],
    relationName: "cover",
  }),
  tags: many(blog_posts_tags, {
    relationName: "tags",
  }),
  author: one(users, {
    fields: [blog_posts.author],
    references: [users.id],
    relationName: "author",
  }),
}));
export const relations_blog_post_localizations = relations(
  blog_post_localizations,
  ({ one }) => ({
    post: one(blog_posts, {
      fields: [blog_post_localizations.post],
      references: [blog_posts.id],
      relationName: "post",
    }),
  }),
);
export const relations_blog_moderation_history = relations(
  blog_moderation_history,
  ({ one }) => ({
    post: one(blog_posts, {
      fields: [blog_moderation_history.post],
      references: [blog_posts.id],
      relationName: "post",
    }),
    author: one(users, {
      fields: [blog_moderation_history.author],
      references: [users.id],
      relationName: "author",
    }),
    actor: one(users, {
      fields: [blog_moderation_history.actor],
      references: [users.id],
      relationName: "actor",
    }),
  }),
);
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    tournamentsID: one(tournaments, {
      fields: [payload_locked_documents_rels.tournamentsID],
      references: [tournaments.id],
      relationName: "tournaments",
    }),
    activitiesID: one(activities, {
      fields: [payload_locked_documents_rels.activitiesID],
      references: [activities.id],
      relationName: "activities",
    }),
    expertsID: one(experts, {
      fields: [payload_locked_documents_rels.expertsID],
      references: [experts.id],
      relationName: "experts",
    }),
    faqsID: one(faqs, {
      fields: [payload_locked_documents_rels.faqsID],
      references: [faqs.id],
      relationName: "faqs",
    }),
    eventsID: one(events, {
      fields: [payload_locked_documents_rels.eventsID],
      references: [events.id],
      relationName: "events",
    }),
    opportunitiesID: one(opportunities, {
      fields: [payload_locked_documents_rels.opportunitiesID],
      references: [opportunities.id],
      relationName: "opportunities",
    }),
    "team-membersID": one(team_members, {
      fields: [payload_locked_documents_rels["team-membersID"]],
      references: [team_members.id],
      relationName: "team-members",
    }),
    "team-postsID": one(team_posts, {
      fields: [payload_locked_documents_rels["team-postsID"]],
      references: [team_posts.id],
      relationName: "team-posts",
    }),
    "team-responsesID": one(team_responses, {
      fields: [payload_locked_documents_rels["team-responsesID"]],
      references: [team_responses.id],
      relationName: "team-responses",
    }),
    "trust-pointsID": one(trust_points, {
      fields: [payload_locked_documents_rels["trust-pointsID"]],
      references: [trust_points.id],
      relationName: "trust-points",
    }),
    pillarsID: one(pillars, {
      fields: [payload_locked_documents_rels.pillarsID],
      references: [pillars.id],
      relationName: "pillars",
    }),
    scenariosID: one(scenarios, {
      fields: [payload_locked_documents_rels.scenariosID],
      references: [scenarios.id],
      relationName: "scenarios",
    }),
    statsID: one(stats, {
      fields: [payload_locked_documents_rels.statsID],
      references: [stats.id],
      relationName: "stats",
    }),
    applicationsID: one(applications, {
      fields: [payload_locked_documents_rels.applicationsID],
      references: [applications.id],
      relationName: "applications",
    }),
    "application-status-historyID": one(application_status_history, {
      fields: [payload_locked_documents_rels["application-status-historyID"]],
      references: [application_status_history.id],
      relationName: "application-status-history",
    }),
    favoritesID: one(favorites, {
      fields: [payload_locked_documents_rels.favoritesID],
      references: [favorites.id],
      relationName: "favorites",
    }),
    notificationsID: one(notifications, {
      fields: [payload_locked_documents_rels.notificationsID],
      references: [notifications.id],
      relationName: "notifications",
    }),
    "community-leadsID": one(community_leads, {
      fields: [payload_locked_documents_rels["community-leadsID"]],
      references: [community_leads.id],
      relationName: "community-leads",
    }),
    "contact-settingsID": one(contact_settings, {
      fields: [payload_locked_documents_rels["contact-settingsID"]],
      references: [contact_settings.id],
      relationName: "contact-settings",
    }),
    "blog-postsID": one(blog_posts, {
      fields: [payload_locked_documents_rels["blog-postsID"]],
      references: [blog_posts.id],
      relationName: "blog-posts",
    }),
    "blog-post-localizationsID": one(blog_post_localizations, {
      fields: [payload_locked_documents_rels["blog-post-localizationsID"]],
      references: [blog_post_localizations.id],
      relationName: "blog-post-localizations",
    }),
    "blog-moderation-historyID": one(blog_moderation_history, {
      fields: [payload_locked_documents_rels["blog-moderation-historyID"]],
      references: [blog_moderation_history.id],
      relationName: "blog-moderation-history",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  users_interests: typeof users_interests;
  users_skills: typeof users_skills;
  users_languages: typeof users_languages;
  users_social_links: typeof users_social_links;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  tournaments_skills: typeof tournaments_skills;
  tournaments_mentors: typeof tournaments_mentors;
  tournaments: typeof tournaments;
  activities_benefits: typeof activities_benefits;
  activities: typeof activities;
  experts: typeof experts;
  faqs: typeof faqs;
  events_languages: typeof events_languages;
  events_materials: typeof events_materials;
  events: typeof events;
  opportunities_languages: typeof opportunities_languages;
  opportunities_requirements: typeof opportunities_requirements;
  opportunities_benefits: typeof opportunities_benefits;
  opportunities_documents: typeof opportunities_documents;
  opportunities: typeof opportunities;
  team_members_interests: typeof team_members_interests;
  team_members_skills: typeof team_members_skills;
  team_members_target_roles: typeof team_members_target_roles;
  team_members: typeof team_members;
  team_posts_required_skills: typeof team_posts_required_skills;
  team_posts_own_skills: typeof team_posts_own_skills;
  team_posts_interests: typeof team_posts_interests;
  team_posts: typeof team_posts;
  team_responses: typeof team_responses;
  trust_points: typeof trust_points;
  pillars: typeof pillars;
  scenarios: typeof scenarios;
  stats: typeof stats;
  applications: typeof applications;
  applications_rels: typeof applications_rels;
  application_status_history: typeof application_status_history;
  favorites: typeof favorites;
  notifications: typeof notifications;
  community_leads: typeof community_leads;
  contact_settings: typeof contact_settings;
  blog_posts_tags: typeof blog_posts_tags;
  blog_posts: typeof blog_posts;
  blog_post_localizations: typeof blog_post_localizations;
  blog_moderation_history: typeof blog_moderation_history;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_interests: typeof relations_users_interests;
  relations_users_skills: typeof relations_users_skills;
  relations_users_languages: typeof relations_users_languages;
  relations_users_social_links: typeof relations_users_social_links;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_tournaments_skills: typeof relations_tournaments_skills;
  relations_tournaments_mentors: typeof relations_tournaments_mentors;
  relations_tournaments: typeof relations_tournaments;
  relations_activities_benefits: typeof relations_activities_benefits;
  relations_activities: typeof relations_activities;
  relations_experts: typeof relations_experts;
  relations_faqs: typeof relations_faqs;
  relations_events_languages: typeof relations_events_languages;
  relations_events_materials: typeof relations_events_materials;
  relations_events: typeof relations_events;
  relations_opportunities_languages: typeof relations_opportunities_languages;
  relations_opportunities_requirements: typeof relations_opportunities_requirements;
  relations_opportunities_benefits: typeof relations_opportunities_benefits;
  relations_opportunities_documents: typeof relations_opportunities_documents;
  relations_opportunities: typeof relations_opportunities;
  relations_team_members_interests: typeof relations_team_members_interests;
  relations_team_members_skills: typeof relations_team_members_skills;
  relations_team_members_target_roles: typeof relations_team_members_target_roles;
  relations_team_members: typeof relations_team_members;
  relations_team_posts_required_skills: typeof relations_team_posts_required_skills;
  relations_team_posts_own_skills: typeof relations_team_posts_own_skills;
  relations_team_posts_interests: typeof relations_team_posts_interests;
  relations_team_posts: typeof relations_team_posts;
  relations_team_responses: typeof relations_team_responses;
  relations_trust_points: typeof relations_trust_points;
  relations_pillars: typeof relations_pillars;
  relations_scenarios: typeof relations_scenarios;
  relations_stats: typeof relations_stats;
  relations_applications_rels: typeof relations_applications_rels;
  relations_applications: typeof relations_applications;
  relations_application_status_history: typeof relations_application_status_history;
  relations_favorites: typeof relations_favorites;
  relations_notifications: typeof relations_notifications;
  relations_community_leads: typeof relations_community_leads;
  relations_contact_settings: typeof relations_contact_settings;
  relations_blog_posts_tags: typeof relations_blog_posts_tags;
  relations_blog_posts: typeof relations_blog_posts;
  relations_blog_post_localizations: typeof relations_blog_post_localizations;
  relations_blog_moderation_history: typeof relations_blog_moderation_history;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
